<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Exercise Answers | Introduction to R for Crime Analysts</title>
  <meta name="description" content="This course is designed to help you transition from SPSS to R, demonstrating that all of the functionality you’re accustomed to in SPSS can be replicated—and often enhanced—in R. By the end of this course, you will be equipped with the knowledge and skills to conduct your analyses in R, whether you’re dealing with basic descriptive statistics, survey data, or more advanced statistical models." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Exercise Answers | Introduction to R for Crime Analysts" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This course is designed to help you transition from SPSS to R, demonstrating that all of the functionality you’re accustomed to in SPSS can be replicated—and often enhanced—in R. By the end of this course, you will be equipped with the knowledge and skills to conduct your analyses in R, whether you’re dealing with basic descriptive statistics, survey data, or more advanced statistical models." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Exercise Answers | Introduction to R for Crime Analysts" />
  
  <meta name="twitter:description" content="This course is designed to help you transition from SPSS to R, demonstrating that all of the functionality you’re accustomed to in SPSS can be replicated—and often enhanced—in R. By the end of this course, you will be equipped with the knowledge and skills to conduct your analyses in R, whether you’re dealing with basic descriptive statistics, survey data, or more advanced statistical models." />
  

<meta name="author" content="Daniel Hammocks, Senior Data Scientist at Mayor’s Office for Policing and Crime" />


<meta name="date" content="2024-08-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="geographic-mapping-and-spatial-analysis.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="images/MOPAC-DS-Square.png"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#purpose-of-this-book"><i class="fa fa-check"></i>Purpose of this Book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i>About the Author</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#overview"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#why-learn-r"><i class="fa fa-check"></i><b>1.2</b> Why Learn R?</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction.html"><a href="introduction.html#flexibility-and-power"><i class="fa fa-check"></i><b>1.2.1</b> Flexibility and Power</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction.html"><a href="introduction.html#reproducibility"><i class="fa fa-check"></i><b>1.2.2</b> Reproducibility</a></li>
<li class="chapter" data-level="1.2.3" data-path="introduction.html"><a href="introduction.html#extensive-community-and-package-ecosystem"><i class="fa fa-check"></i><b>1.2.3</b> Extensive Community and Package Ecosystem</a></li>
<li class="chapter" data-level="1.2.4" data-path="introduction.html"><a href="introduction.html#cost"><i class="fa fa-check"></i><b>1.2.4</b> Cost</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#replicating-spss-functionality-in-r"><i class="fa fa-check"></i><b>1.3</b> Replicating SPSS Functionality in R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction.html"><a href="introduction.html#data-management"><i class="fa fa-check"></i><b>1.3.1</b> Data Management</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction.html"><a href="introduction.html#descriptive-statistics"><i class="fa fa-check"></i><b>1.3.2</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction.html"><a href="introduction.html#statistical-tests"><i class="fa fa-check"></i><b>1.3.3</b> Statistical Tests</a></li>
<li class="chapter" data-level="1.3.4" data-path="introduction.html"><a href="introduction.html#regression-analysis"><i class="fa fa-check"></i><b>1.3.4</b> Regression Analysis</a></li>
<li class="chapter" data-level="1.3.5" data-path="introduction.html"><a href="introduction.html#data-visualisation"><i class="fa fa-check"></i><b>1.3.5</b> Data Visualisation</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#transitioning-from-spss-to-r"><i class="fa fa-check"></i><b>1.4</b> Transitioning from SPSS to R</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction.html"><a href="introduction.html#building-confidence-in-r"><i class="fa fa-check"></i><b>1.4.1</b> Building Confidence in R</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction.html"><a href="introduction.html#leveraging-rs-ecosystem"><i class="fa fa-check"></i><b>1.4.2</b> Leveraging R’s Ecosystem</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#conclusion"><i class="fa fa-check"></i><b>1.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html"><i class="fa fa-check"></i><b>2</b> Getting Started with R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#the-r-environment"><i class="fa fa-check"></i><b>2.1</b> The R Environment</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#overview-of-the-rstudio-interface"><i class="fa fa-check"></i><b>2.1.1</b> Overview of the RStudio Interface</a></li>
<li class="chapter" data-level="2.1.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#console-vs.-scripts-vs.-notebooks"><i class="fa fa-check"></i><b>2.1.2</b> Console vs. Scripts vs. Notebooks</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#introduction-to-r-packages-and-installing-key-packages"><i class="fa fa-check"></i><b>2.2</b> Introduction to R Packages and Installing Key Packages</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#introduction-to-r-packages"><i class="fa fa-check"></i><b>2.2.1</b> Introduction to R Packages</a></li>
<li class="chapter" data-level="2.2.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>2.2.2</b> Installing and Loading Packages</a></li>
<li class="chapter" data-level="2.2.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#key-packages-for-data-analysis"><i class="fa fa-check"></i><b>2.2.3</b> Key Packages for Data Analysis</a></li>
<li class="chapter" data-level="2.2.4" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#managing-package-dependencies"><i class="fa fa-check"></i><b>2.2.4</b> Managing Package Dependencies</a></li>
<li class="chapter" data-level="2.2.5" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#summary"><i class="fa fa-check"></i><b>2.2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#coding-conventions-and-best-practices"><i class="fa fa-check"></i><b>2.3</b> Coding Conventions and Best Practices</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#writing-clean-and-readable-code"><i class="fa fa-check"></i><b>2.3.1</b> Writing Clean and Readable Code</a></li>
<li class="chapter" data-level="2.3.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#commenting-and-structuring-scripts"><i class="fa fa-check"></i><b>2.3.2</b> Commenting and Structuring Scripts</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#data-types-and-structures"><i class="fa fa-check"></i><b>2.4</b> Data Types and Structures</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#introduction-to-vectors-data-frames-lists-and-factors"><i class="fa fa-check"></i><b>2.4.1</b> Introduction to Vectors, Data Frames, Lists, and Factors</a></li>
<li class="chapter" data-level="2.4.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#comparing-r-data-types-to-spss-data-types"><i class="fa fa-check"></i><b>2.4.2</b> Comparing R Data Types to SPSS Data Types</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#basic-operations-and-functions-in-r"><i class="fa fa-check"></i><b>2.5</b> Basic Operations and Functions in R</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#arithmetic-operations"><i class="fa fa-check"></i><b>2.5.1</b> Arithmetic Operations</a></li>
<li class="chapter" data-level="2.5.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#logical-operations"><i class="fa fa-check"></i><b>2.5.2</b> Logical Operations</a></li>
<li class="chapter" data-level="2.5.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#basic-functions"><i class="fa fa-check"></i><b>2.5.3</b> Basic Functions</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#conclusion-1"><i class="fa fa-check"></i><b>2.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-management-in-r.html"><a href="data-management-in-r.html"><i class="fa fa-check"></i><b>3</b> Data Management in R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-management-in-r.html"><a href="data-management-in-r.html#data-import-and-export"><i class="fa fa-check"></i><b>3.1</b> Data Import and Export</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-management-in-r.html"><a href="data-management-in-r.html#importing-data"><i class="fa fa-check"></i><b>3.1.1</b> Importing Data</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-management-in-r.html"><a href="data-management-in-r.html#exporting-data"><i class="fa fa-check"></i><b>3.1.2</b> Exporting Data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-management-in-r.html"><a href="data-management-in-r.html#data-cleaning-and-preparation"><i class="fa fa-check"></i><b>3.2</b> Data Cleaning and Preparation</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-management-in-r.html"><a href="data-management-in-r.html#handling-missing-data"><i class="fa fa-check"></i><b>3.2.1</b> Handling Missing Data</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-management-in-r.html"><a href="data-management-in-r.html#filtering-and-subsetting-data"><i class="fa fa-check"></i><b>3.2.2</b> Filtering and Subsetting Data</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-management-in-r.html"><a href="data-management-in-r.html#data-transformations"><i class="fa fa-check"></i><b>3.2.3</b> Data Transformations</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-management-in-r.html"><a href="data-management-in-r.html#the-dplyr-pipeline"><i class="fa fa-check"></i><b>3.2.4</b> The dplyr Pipeline</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-management-in-r.html"><a href="data-management-in-r.html#working-with-categorical-data"><i class="fa fa-check"></i><b>3.3</b> Working with Categorical Data</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-management-in-r.html"><a href="data-management-in-r.html#creating-and-manipulating-factors"><i class="fa fa-check"></i><b>3.3.1</b> Creating and Manipulating Factors</a></li>
<li class="chapter" data-level="3.3.2" data-path="data-management-in-r.html"><a href="data-management-in-r.html#recoding-variables"><i class="fa fa-check"></i><b>3.3.2</b> Recoding Variables</a></li>
<li class="chapter" data-level="3.3.3" data-path="data-management-in-r.html"><a href="data-management-in-r.html#frequency-tables-and-cross-tabulations"><i class="fa fa-check"></i><b>3.3.3</b> Frequency Tables and Cross-Tabulations</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-management-in-r.html"><a href="data-management-in-r.html#conclusion-2"><i class="fa fa-check"></i><b>3.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="connecting-to-and-accessing-a-postgresql-database.html"><a href="connecting-to-and-accessing-a-postgresql-database.html"><i class="fa fa-check"></i><b>4</b> Connecting to and Accessing a PostgreSQL Database</a>
<ul>
<li class="chapter" data-level="4.1" data-path="connecting-to-and-accessing-a-postgresql-database.html"><a href="connecting-to-and-accessing-a-postgresql-database.html#introduction-1"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="connecting-to-and-accessing-a-postgresql-database.html"><a href="connecting-to-and-accessing-a-postgresql-database.html#setting-up-the-environment"><i class="fa fa-check"></i><b>4.2</b> Setting Up the Environment</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="connecting-to-and-accessing-a-postgresql-database.html"><a href="connecting-to-and-accessing-a-postgresql-database.html#installing-necessary-packages"><i class="fa fa-check"></i><b>4.2.1</b> Installing Necessary Packages</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="connecting-to-and-accessing-a-postgresql-database.html"><a href="connecting-to-and-accessing-a-postgresql-database.html#connecting-to-postgresql-using-rpostgres"><i class="fa fa-check"></i><b>4.3</b> Connecting to PostgreSQL (Using RPostgres)</a></li>
<li class="chapter" data-level="4.4" data-path="connecting-to-and-accessing-a-postgresql-database.html"><a href="connecting-to-and-accessing-a-postgresql-database.html#querying-data-from-postgresql"><i class="fa fa-check"></i><b>4.4</b> Querying Data from PostgreSQL</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="connecting-to-and-accessing-a-postgresql-database.html"><a href="connecting-to-and-accessing-a-postgresql-database.html#executing-a-query"><i class="fa fa-check"></i><b>4.4.1</b> Executing a Query</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="connecting-to-and-accessing-a-postgresql-database.html"><a href="connecting-to-and-accessing-a-postgresql-database.html#handling-errors-and-troubleshooting"><i class="fa fa-check"></i><b>4.5</b> Handling Errors and Troubleshooting</a></li>
<li class="chapter" data-level="4.6" data-path="connecting-to-and-accessing-a-postgresql-database.html"><a href="connecting-to-and-accessing-a-postgresql-database.html#conclusion-3"><i class="fa fa-check"></i><b>4.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html"><i class="fa fa-check"></i><b>5</b> Descriptive Statistics and Visualisations</a>
<ul>
<li class="chapter" data-level="5.1" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#introduction-to-descriptive-statistics"><i class="fa fa-check"></i><b>5.1</b> Introduction to Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#understanding-descriptive-statistics"><i class="fa fa-check"></i><b>5.1.1</b> Understanding Descriptive Statistics</a></li>
<li class="chapter" data-level="5.1.2" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#basic-descriptive-statistics-in-r"><i class="fa fa-check"></i><b>5.1.2</b> Basic Descriptive Statistics in R</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#creating-visualisations-with-ggplot2"><i class="fa fa-check"></i><b>5.2</b> Creating Visualisations with ggplot2</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#introduction-to-ggplot2"><i class="fa fa-check"></i><b>5.2.1</b> Introduction to ggplot2</a></li>
<li class="chapter" data-level="5.2.2" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#creating-basic-plots"><i class="fa fa-check"></i><b>5.2.2</b> Creating Basic Plots</a></li>
<li class="chapter" data-level="5.2.3" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#customising-your-plots"><i class="fa fa-check"></i><b>5.2.3</b> Customising Your Plots</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#descriptive-statistics-with-dplyr"><i class="fa fa-check"></i><b>5.3</b> Descriptive Statistics with dplyr</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#using-dplyr-to-summarise-data"><i class="fa fa-check"></i><b>5.3.1</b> Using dplyr to Summarise Data</a></li>
<li class="chapter" data-level="5.3.2" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#combining-dplyr-with-ggplot2"><i class="fa fa-check"></i><b>5.3.2</b> Combining dplyr with ggplot2</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#advanced-visualisation-techniques"><i class="fa fa-check"></i><b>5.4</b> Advanced Visualisation Techniques</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#faceting"><i class="fa fa-check"></i><b>5.4.1</b> Faceting</a></li>
<li class="chapter" data-level="5.4.2" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#combining-multiple-geoms"><i class="fa fa-check"></i><b>5.4.2</b> Combining Multiple Geoms</a></li>
<li class="chapter" data-level="5.4.3" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#saving-your-plots"><i class="fa fa-check"></i><b>5.4.3</b> Saving Your Plots</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="descriptive-statistics-and-visualisations.html"><a href="descriptive-statistics-and-visualisations.html#conclusion-4"><i class="fa fa-check"></i><b>5.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html"><i class="fa fa-check"></i><b>6</b> Survey Analysis in R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#introduction-to-survey-data"><i class="fa fa-check"></i><b>6.1</b> Introduction to Survey Data</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#key-concepts-in-survey-analysis"><i class="fa fa-check"></i><b>6.1.1</b> Key Concepts in Survey Analysis</a></li>
<li class="chapter" data-level="6.1.2" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#understanding-survey-data-structures"><i class="fa fa-check"></i><b>6.1.2</b> Understanding Survey Data Structures</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#importing-and-preparing-survey-data"><i class="fa fa-check"></i><b>6.2</b> Importing and Preparing Survey Data</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#converting-data-for-survey-analysis"><i class="fa fa-check"></i><b>6.2.1</b> Converting Data for Survey Analysis</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#descriptive-analysis-of-survey-data"><i class="fa fa-check"></i><b>6.3</b> Descriptive Analysis of Survey Data</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#calculating-means-and-totals"><i class="fa fa-check"></i><b>6.3.1</b> Calculating Means and Totals</a></li>
<li class="chapter" data-level="6.3.2" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#frequencies-and-cross-tabulations"><i class="fa fa-check"></i><b>6.3.2</b> Frequencies and Cross-tabulations</a></li>
<li class="chapter" data-level="6.3.3" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#comparing-results-with-spss-survey-functions"><i class="fa fa-check"></i><b>6.3.3</b> Comparing Results with SPSS Survey Functions</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#weighting-survey-data"><i class="fa fa-check"></i><b>6.4</b> Weighting Survey Data</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#applying-weights"><i class="fa fa-check"></i><b>6.4.1</b> Applying Weights</a></li>
<li class="chapter" data-level="6.4.2" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#analysing-weighted-survey-data"><i class="fa fa-check"></i><b>6.4.2</b> Analysing Weighted Survey Data</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="survey-analysis-in-r.html"><a href="survey-analysis-in-r.html#conclusion-5"><i class="fa fa-check"></i><b>6.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="inferential-statistics.html"><a href="inferential-statistics.html"><i class="fa fa-check"></i><b>7</b> Inferential Statistics</a>
<ul>
<li class="chapter" data-level="7.1" data-path="inferential-statistics.html"><a href="inferential-statistics.html#hypothesis-testing"><i class="fa fa-check"></i><b>7.1</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="inferential-statistics.html"><a href="inferential-statistics.html#t-tests"><i class="fa fa-check"></i><b>7.1.1</b> T-tests</a></li>
<li class="chapter" data-level="7.1.2" data-path="inferential-statistics.html"><a href="inferential-statistics.html#chi-square-tests"><i class="fa fa-check"></i><b>7.1.2</b> Chi-square Tests</a></li>
<li class="chapter" data-level="7.1.3" data-path="inferential-statistics.html"><a href="inferential-statistics.html#anova-analysis-of-variance"><i class="fa fa-check"></i><b>7.1.3</b> ANOVA (Analysis of Variance)</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="inferential-statistics.html"><a href="inferential-statistics.html#correlation-analysis"><i class="fa fa-check"></i><b>7.2</b> Correlation Analysis</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="inferential-statistics.html"><a href="inferential-statistics.html#pearson-correlation"><i class="fa fa-check"></i><b>7.2.1</b> Pearson Correlation</a></li>
<li class="chapter" data-level="7.2.2" data-path="inferential-statistics.html"><a href="inferential-statistics.html#spearman-correlation"><i class="fa fa-check"></i><b>7.2.2</b> Spearman Correlation</a></li>
<li class="chapter" data-level="7.2.3" data-path="inferential-statistics.html"><a href="inferential-statistics.html#pearson-vs-spearman"><i class="fa fa-check"></i><b>7.2.3</b> Pearson vs Spearman?</a></li>
<li class="chapter" data-level="7.2.4" data-path="inferential-statistics.html"><a href="inferential-statistics.html#visualising-correlations"><i class="fa fa-check"></i><b>7.2.4</b> Visualising Correlations</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="inferential-statistics.html"><a href="inferential-statistics.html#conclusion-6"><i class="fa fa-check"></i><b>7.3</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html"><i class="fa fa-check"></i><b>8</b> Regression Analysis</a>
<ul>
<li class="chapter" data-level="8.1" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#introduction-to-regression-analysis"><i class="fa fa-check"></i><b>8.1</b> Introduction to Regression Analysis</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#what-is-linear-regression"><i class="fa fa-check"></i><b>8.1.1</b> What is Linear Regression?</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#simple-linear-regression-in-r"><i class="fa fa-check"></i><b>8.2</b> Simple Linear Regression in R</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#performing-simple-linear-regression"><i class="fa fa-check"></i><b>8.2.1</b> Performing Simple Linear Regression</a></li>
<li class="chapter" data-level="8.2.2" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#interpreting-the-output"><i class="fa fa-check"></i><b>8.2.2</b> Interpreting the Output</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#multiple-linear-regression"><i class="fa fa-check"></i><b>8.3</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#performing-multiple-linear-regression"><i class="fa fa-check"></i><b>8.3.1</b> Performing Multiple Linear Regression</a></li>
<li class="chapter" data-level="8.3.2" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#detailed-interpretation-of-the-output"><i class="fa fa-check"></i><b>8.3.2</b> Detailed Interpretation of the Output</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#checking-model-assumptions"><i class="fa fa-check"></i><b>8.4</b> Checking Model Assumptions</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#assumption-1-linearity"><i class="fa fa-check"></i><b>8.4.1</b> Assumption 1: Linearity</a></li>
<li class="chapter" data-level="8.4.2" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#assumption-2-normality-of-residuals"><i class="fa fa-check"></i><b>8.4.2</b> Assumption 2: Normality of Residuals</a></li>
<li class="chapter" data-level="8.4.3" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#assumption-3-homoscedasticity"><i class="fa fa-check"></i><b>8.4.3</b> Assumption 3: Homoscedasticity</a></li>
<li class="chapter" data-level="8.4.4" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#assumption-4-independence-of-errors"><i class="fa fa-check"></i><b>8.4.4</b> Assumption 4: Independence of Errors</a></li>
<li class="chapter" data-level="8.4.5" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#assumption-5-multicollinearity"><i class="fa fa-check"></i><b>8.4.5</b> Assumption 5: Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#transformations-and-interaction-terms"><i class="fa fa-check"></i><b>8.5</b> Transformations and Interaction Terms</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#when-and-how-to-apply-transformations"><i class="fa fa-check"></i><b>8.5.1</b> When and How to Apply Transformations</a></li>
<li class="chapter" data-level="8.5.2" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#using-interaction-terms"><i class="fa fa-check"></i><b>8.5.2</b> Using Interaction Terms</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#logistic-regression"><i class="fa fa-check"></i><b>8.6</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#performing-logistic-regression-in-r"><i class="fa fa-check"></i><b>8.6.1</b> Performing Logistic Regression in R</a></li>
<li class="chapter" data-level="8.6.2" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#interpreting-logistic-regression-output"><i class="fa fa-check"></i><b>8.6.2</b> Interpreting Logistic Regression Output</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#checking-model-assumptions-for-logistic-regression"><i class="fa fa-check"></i><b>8.7</b> Checking Model Assumptions for Logistic Regression</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#assumption-1-linearity-of-the-logit"><i class="fa fa-check"></i><b>8.7.1</b> Assumption 1: Linearity of the Logit</a></li>
<li class="chapter" data-level="8.7.2" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#assumption-2-independence-of-observations"><i class="fa fa-check"></i><b>8.7.2</b> Assumption 2: Independence of Observations</a></li>
<li class="chapter" data-level="8.7.3" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#assumption-3-absence-of-multicollinearity"><i class="fa fa-check"></i><b>8.7.3</b> Assumption 3: Absence of Multicollinearity</a></li>
<li class="chapter" data-level="8.7.4" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#assumption-4-sufficient-sample-size"><i class="fa fa-check"></i><b>8.7.4</b> Assumption 4: Sufficient Sample Size</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#model-validation-and-diagnostics"><i class="fa fa-check"></i><b>8.8</b> Model Validation and Diagnostics</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#cross-validation"><i class="fa fa-check"></i><b>8.8.1</b> Cross-Validation</a></li>
<li class="chapter" data-level="8.8.2" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#dealing-with-overfitting"><i class="fa fa-check"></i><b>8.8.2</b> Dealing with Overfitting</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="regression-analysis-1.html"><a href="regression-analysis-1.html#conclusion-7"><i class="fa fa-check"></i><b>8.9</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html"><i class="fa fa-check"></i><b>9</b> Geographic Mapping and Spatial Analysis</a>
<ul>
<li class="chapter" data-level="9.1" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#introduction-to-geographic-data-in-r"><i class="fa fa-check"></i><b>9.1</b> Introduction to Geographic Data in R</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#understanding-geographic-data-formats"><i class="fa fa-check"></i><b>9.1.1</b> Understanding Geographic Data Formats</a></li>
<li class="chapter" data-level="9.1.2" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#importing-and-handling-spatial-data-with-the-sf-package"><i class="fa fa-check"></i><b>9.1.2</b> Importing and Handling Spatial Data with the <code>sf</code> Package</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#geographic-coordinate-systems-and-projections"><i class="fa fa-check"></i><b>9.2</b> Geographic Coordinate Systems and Projections</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#introduction-to-coordinate-systems"><i class="fa fa-check"></i><b>9.2.1</b> Introduction to Coordinate Systems</a></li>
<li class="chapter" data-level="9.2.2" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#common-issues-with-coordinate-systems-in-r"><i class="fa fa-check"></i><b>9.2.2</b> Common Issues with Coordinate Systems in R</a></li>
<li class="chapter" data-level="9.2.3" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#handling-coordinate-systems-in-r"><i class="fa fa-check"></i><b>9.2.3</b> Handling Coordinate Systems in R</a></li>
<li class="chapter" data-level="9.2.4" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#practical-considerations"><i class="fa fa-check"></i><b>9.2.4</b> Practical Considerations</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#creating-basic-maps"><i class="fa fa-check"></i><b>9.3</b> Creating Basic Maps</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#plotting-data-on-maps-using-ggplot2-and-sf"><i class="fa fa-check"></i><b>9.3.1</b> Plotting Data on Maps Using ggplot2 and sf</a></li>
<li class="chapter" data-level="9.3.2" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#customising-maps"><i class="fa fa-check"></i><b>9.3.2</b> Customising Maps</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#spatial-analysis"><i class="fa fa-check"></i><b>9.4</b> Spatial Analysis</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#basic-spatial-operations"><i class="fa fa-check"></i><b>9.4.1</b> Basic Spatial Operations</a></li>
<li class="chapter" data-level="9.4.2" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#creating-choropleth-maps"><i class="fa fa-check"></i><b>9.4.2</b> Creating Choropleth Maps</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="geographic-mapping-and-spatial-analysis.html"><a href="geographic-mapping-and-spatial-analysis.html#conclusion-8"><i class="fa fa-check"></i><b>9.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html"><i class="fa fa-check"></i>Exercise Answers</a>
<ul>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#chapter-2"><i class="fa fa-check"></i>Chapter 2</a>
<ul>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-2.1"><i class="fa fa-check"></i>Exercise 2.1</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-2.2"><i class="fa fa-check"></i>Exercise 2.2</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-2.3"><i class="fa fa-check"></i>Exercise 2.3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#chapter-3"><i class="fa fa-check"></i>Chapter 3</a>
<ul>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-3.1"><i class="fa fa-check"></i>Exercise 3.1</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-3.2"><i class="fa fa-check"></i>Exercise 3.2</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-3.3"><i class="fa fa-check"></i>Exercise 3.3</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-3.4"><i class="fa fa-check"></i>Exercise 3.4</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-3.5"><i class="fa fa-check"></i>Exercise 3.5</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-3.6"><i class="fa fa-check"></i>Exercise 3.6</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-3.7"><i class="fa fa-check"></i>Exercise 3.7</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-3.8"><i class="fa fa-check"></i>Exercise 3.8</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#chapter-5"><i class="fa fa-check"></i>Chapter 5</a>
<ul>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-5.1"><i class="fa fa-check"></i>Exercise 5.1</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#excercise-5.2"><i class="fa fa-check"></i>Excercise 5.2</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-5.3"><i class="fa fa-check"></i>Exercise 5.3</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-5.4"><i class="fa fa-check"></i>Exercise 5.4</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-5.6"><i class="fa fa-check"></i>Exercise 5.6</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-5.7"><i class="fa fa-check"></i>Exercise 5.7</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-5.8"><i class="fa fa-check"></i>Exercise 5.8</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#excerise-5.9"><i class="fa fa-check"></i>Excerise 5.9</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-5.10"><i class="fa fa-check"></i>Exercise 5.10</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#chapter-6"><i class="fa fa-check"></i>Chapter 6</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#chapter-7"><i class="fa fa-check"></i>Chapter 7</a>
<ul>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-7.1"><i class="fa fa-check"></i>Exercise 7.1</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-7.2"><i class="fa fa-check"></i>Exercise 7.2</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-7.3"><i class="fa fa-check"></i>Exercise 7.3</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-7.4"><i class="fa fa-check"></i>Exercise 7.4</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#chapter-8"><i class="fa fa-check"></i>Chapter 8</a>
<ul>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-8.1"><i class="fa fa-check"></i>Exercise 8.1</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-8.2"><i class="fa fa-check"></i>Exercise 8.2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#chapter-9"><i class="fa fa-check"></i>Chapter 9</a>
<ul>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-9.1"><i class="fa fa-check"></i>Exercise 9.1</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-9.2"><i class="fa fa-check"></i>Exercise 9.2</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-9.3"><i class="fa fa-check"></i>Exercise 9.3</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-9.4"><i class="fa fa-check"></i>Exercise 9.4</a></li>
<li class="chapter" data-level="" data-path="exercise-answers.html"><a href="exercise-answers.html#exercise-9.5"><i class="fa fa-check"></i>Exercise 9.5</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to R for Crime Analysts</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="exercise-answers" class="section level1 unnumbered hasAnchor">
<h1>Exercise Answers<a href="exercise-answers.html#exercise-answers" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="chapter-2" class="section level2 unnumbered hasAnchor">
<h2>Chapter 2<a href="exercise-answers.html#chapter-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="exercise-2.1" class="section level3 unnumbered hasAnchor">
<h3>Exercise 2.1<a href="exercise-answers.html#exercise-2.1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Execute these operations in R and compare with results from SPSS’s Compute function. Can you do this in both the console and the script editor?</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="exercise-answers.html#cb164-1" tabindex="-1"></a>addition <span class="ot">&lt;-</span> <span class="dv">5</span> <span class="sc">+</span> <span class="dv">3</span></span>
<span id="cb164-2"><a href="exercise-answers.html#cb164-2" tabindex="-1"></a>subtraction <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="sc">-</span> <span class="dv">4</span></span>
<span id="cb164-3"><a href="exercise-answers.html#cb164-3" tabindex="-1"></a>multiplication <span class="ot">&lt;-</span> <span class="dv">7</span> <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb164-4"><a href="exercise-answers.html#cb164-4" tabindex="-1"></a>division <span class="ot">&lt;-</span> <span class="dv">8</span> <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb164-5"><a href="exercise-answers.html#cb164-5" tabindex="-1"></a>exponentiation <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">^</span><span class="dv">3</span></span></code></pre></div>
</div>
<div id="exercise-2.2" class="section level3 unnumbered hasAnchor">
<h3>Exercise 2.2<a href="exercise-answers.html#exercise-2.2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Test these logical operations in R and compare them to SPSS’s logical operators.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="exercise-answers.html#cb165-1" tabindex="-1"></a><span class="co"># Logical operations</span></span>
<span id="cb165-2"><a href="exercise-answers.html#cb165-2" tabindex="-1"></a>equal <span class="ot">&lt;-</span> (<span class="dv">5</span> <span class="sc">==</span> <span class="dv">5</span>)  <span class="co"># TRUE</span></span>
<span id="cb165-3"><a href="exercise-answers.html#cb165-3" tabindex="-1"></a>not_equal <span class="ot">&lt;-</span> (<span class="dv">5</span> <span class="sc">!=</span> <span class="dv">3</span>)  <span class="co"># TRUE</span></span>
<span id="cb165-4"><a href="exercise-answers.html#cb165-4" tabindex="-1"></a>greater_than <span class="ot">&lt;-</span> (<span class="dv">5</span> <span class="sc">&gt;</span> <span class="dv">3</span>)  <span class="co"># TRUE</span></span>
<span id="cb165-5"><a href="exercise-answers.html#cb165-5" tabindex="-1"></a>and_operation <span class="ot">&lt;-</span> (<span class="dv">5</span> <span class="sc">&gt;</span> <span class="dv">3</span> <span class="sc">&amp;</span> <span class="dv">4</span> <span class="sc">&lt;</span> <span class="dv">6</span>)  <span class="co"># TRUE</span></span>
<span id="cb165-6"><a href="exercise-answers.html#cb165-6" tabindex="-1"></a>or_operation <span class="ot">&lt;-</span> (<span class="dv">5</span> <span class="sc">&gt;</span> <span class="dv">6</span> <span class="sc">|</span> <span class="dv">4</span> <span class="sc">&lt;</span> <span class="dv">6</span>)  <span class="co"># TRUE</span></span></code></pre></div>
</div>
<div id="exercise-2.3" class="section level3 unnumbered hasAnchor">
<h3>Exercise 2.3<a href="exercise-answers.html#exercise-2.3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Between January 2023 and December 2023 the number of Violent and Sexual Offences in Wandsworth were as follows: 568, 568, 603, 604, 685, 871, 697, 608, 657, 681, 630, and 720. (1) Create a vector representing the number of Violent and Sexual Offences in Wandsworth. (2) What was the mean number of crimes each month? (3) What was the total number of crimes across the year? (4) What is the length of the vector?</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="exercise-answers.html#cb166-1" tabindex="-1"></a><span class="co">#Create a vector representing all Violent &amp; Sexual Offences in Wandsworth in 2023</span></span>
<span id="cb166-2"><a href="exercise-answers.html#cb166-2" tabindex="-1"></a>wandsworth_vso_2023 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">568</span>, <span class="dv">568</span>, <span class="dv">603</span>, <span class="dv">604</span>, <span class="dv">685</span>, <span class="dv">871</span>, <span class="dv">697</span>, <span class="dv">608</span>, <span class="dv">657</span>, <span class="dv">681</span>, <span class="dv">630</span>, <span class="dv">720</span>)</span>
<span id="cb166-3"><a href="exercise-answers.html#cb166-3" tabindex="-1"></a></span>
<span id="cb166-4"><a href="exercise-answers.html#cb166-4" tabindex="-1"></a><span class="co">#Calculate the Monthly Average</span></span>
<span id="cb166-5"><a href="exercise-answers.html#cb166-5" tabindex="-1"></a>mean_wandsworth_vso_2023 <span class="ot">&lt;-</span> <span class="fu">mean</span>(wandsworth_vso_2023)</span>
<span id="cb166-6"><a href="exercise-answers.html#cb166-6" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&quot;Mean Number of Monthly V&amp;S Offences in Wandsworth in 2023: &quot;</span>, mean_wandsworth_vso_2023)</span></code></pre></div>
<pre><code>## [1] &quot;Mean Number of Monthly V&amp;S Offences in Wandsworth in 2023:  657.666666666667&quot;</code></pre>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="exercise-answers.html#cb168-1" tabindex="-1"></a><span class="co">#Total Number of Crimes</span></span>
<span id="cb168-2"><a href="exercise-answers.html#cb168-2" tabindex="-1"></a>total_wandsworth_vso_2023 <span class="ot">&lt;-</span> <span class="fu">sum</span>(wandsworth_vso_2023)</span>
<span id="cb168-3"><a href="exercise-answers.html#cb168-3" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&quot;Total Number of V&amp;S Offences in Wandsworth in 2023: &quot;</span>, total_wandsworth_vso_2023)</span></code></pre></div>
<pre><code>## [1] &quot;Total Number of V&amp;S Offences in Wandsworth in 2023:  7892&quot;</code></pre>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="exercise-answers.html#cb170-1" tabindex="-1"></a><span class="co">#Length of Vector</span></span>
<span id="cb170-2"><a href="exercise-answers.html#cb170-2" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&quot;Length of Vector: &quot;</span>, <span class="fu">length</span>(wandsworth_vso_2023))</span></code></pre></div>
<pre><code>## [1] &quot;Length of Vector:  12&quot;</code></pre>
</div>
</div>
<div id="chapter-3" class="section level2 unnumbered hasAnchor">
<h2>Chapter 3<a href="exercise-answers.html#chapter-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="exercise-3.1" class="section level3 unnumbered hasAnchor">
<h3>Exercise 3.1<a href="exercise-answers.html#exercise-3.1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Go to <a href="https://data.police.uk/data/" class="uri">https://data.police.uk/data/</a> and download a CSV file of Metropolitan Police Service data for January 2024. Load the CSV file into a R dataframe called data_mps. How many observations and variables are there?</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="exercise-answers.html#cb172-1" tabindex="-1"></a><span class="co">#Load the data from CSV file</span></span>
<span id="cb172-2"><a href="exercise-answers.html#cb172-2" tabindex="-1"></a>mps_2024_01 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;data/2024-01-metropolitan-street.csv&#39;</span>)</span>
<span id="cb172-3"><a href="exercise-answers.html#cb172-3" tabindex="-1"></a></span>
<span id="cb172-4"><a href="exercise-answers.html#cb172-4" tabindex="-1"></a><span class="co">#Return the size</span></span>
<span id="cb172-5"><a href="exercise-answers.html#cb172-5" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&quot;Number of Observations: &quot;</span>, <span class="fu">dim</span>(mps_2024_01)[<span class="dv">1</span>])</span></code></pre></div>
<pre><code>## [1] &quot;Number of Observations:  91411&quot;</code></pre>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="exercise-answers.html#cb174-1" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&quot;Number of Variables: &quot;</span>, <span class="fu">dim</span>(mps_2024_01)[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>## [1] &quot;Number of Variables:  12&quot;</code></pre>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="exercise-answers.html#cb176-1" tabindex="-1"></a><span class="do">## Note that dim() finds the dimensions of the given variable and [1] or [1] indexes this to take the first or second part.</span></span>
<span id="cb176-2"><a href="exercise-answers.html#cb176-2" tabindex="-1"></a><span class="do">## Alternatively, you coudl find this in the environment pane.</span></span></code></pre></div>
</div>
<div id="exercise-3.2" class="section level3 unnumbered hasAnchor">
<h3>Exercise 3.2<a href="exercise-answers.html#exercise-3.2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Some of the commands above are composite commands encompassing multiple functions. Can you break them down to understand what each part of the function is doing?</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="exercise-answers.html#cb177-1" tabindex="-1"></a><span class="co"># Remove any columns with missing data</span></span>
<span id="cb177-2"><a href="exercise-answers.html#cb177-2" tabindex="-1"></a>data_mps_clean <span class="ot">&lt;-</span> data_mps[, <span class="fu">colSums</span>(<span class="fu">is.na</span>(data_mps)) <span class="sc">==</span> <span class="dv">0</span>]</span>
<span id="cb177-3"><a href="exercise-answers.html#cb177-3" tabindex="-1"></a></span>
<span id="cb177-4"><a href="exercise-answers.html#cb177-4" tabindex="-1"></a>  <span class="co"># is.na(data_mps) identifies any NA values returning a Boolean, 1 = Yes, 0 = No</span></span>
<span id="cb177-5"><a href="exercise-answers.html#cb177-5" tabindex="-1"></a>  <span class="co"># colSums(x) adds the values in each column</span></span>
<span id="cb177-6"><a href="exercise-answers.html#cb177-6" tabindex="-1"></a>  <span class="co"># data_mps[, x] subsets the data to only select column x</span></span>
<span id="cb177-7"><a href="exercise-answers.html#cb177-7" tabindex="-1"></a></span>
<span id="cb177-8"><a href="exercise-answers.html#cb177-8" tabindex="-1"></a>  <span class="co"># Together, this function identifies the columns with no missing values,</span></span>
<span id="cb177-9"><a href="exercise-answers.html#cb177-9" tabindex="-1"></a>  <span class="co"># Produces a cleaned subset by dropping an columns with missing values</span></span>
<span id="cb177-10"><a href="exercise-answers.html#cb177-10" tabindex="-1"></a></span>
<span id="cb177-11"><a href="exercise-answers.html#cb177-11" tabindex="-1"></a></span>
<span id="cb177-12"><a href="exercise-answers.html#cb177-12" tabindex="-1"></a><span class="co"># Replace missing values with a specific value, such as 0.</span></span>
<span id="cb177-13"><a href="exercise-answers.html#cb177-13" tabindex="-1"></a>data_mps[<span class="fu">is.na</span>(data_mps)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb177-14"><a href="exercise-answers.html#cb177-14" tabindex="-1"></a></span>
<span id="cb177-15"><a href="exercise-answers.html#cb177-15" tabindex="-1"></a>  <span class="co"># is.na(data_mps) identifies any NA values returning a Boolean, 1 = Yes, 0 = No</span></span>
<span id="cb177-16"><a href="exercise-answers.html#cb177-16" tabindex="-1"></a>  <span class="co"># data_mps[x] &lt;- 0 sets the value x to zero</span></span>
<span id="cb177-17"><a href="exercise-answers.html#cb177-17" tabindex="-1"></a></span>
<span id="cb177-18"><a href="exercise-answers.html#cb177-18" tabindex="-1"></a>  <span class="co"># Together, this function identifies the missing data</span></span>
<span id="cb177-19"><a href="exercise-answers.html#cb177-19" tabindex="-1"></a>  <span class="co"># Replaces the missing value with a 0.</span></span>
<span id="cb177-20"><a href="exercise-answers.html#cb177-20" tabindex="-1"></a></span>
<span id="cb177-21"><a href="exercise-answers.html#cb177-21" tabindex="-1"></a><span class="co">#Replace missing values with a column value (e.g. Mode, Mean, ...)</span></span>
<span id="cb177-22"><a href="exercise-answers.html#cb177-22" tabindex="-1"></a>data_mps<span class="sc">$</span>Latitude[<span class="fu">is.na</span>(data_mps<span class="sc">$</span>Latitude)] <span class="ot">&lt;-</span> <span class="fu">mean</span>(data_mps<span class="sc">$</span>Latitude, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb177-23"><a href="exercise-answers.html#cb177-23" tabindex="-1"></a></span>
<span id="cb177-24"><a href="exercise-answers.html#cb177-24" tabindex="-1"></a>  <span class="co"># mean(data_mps$Latitude, na.rm = TRUE) calculates the average latitude</span></span>
<span id="cb177-25"><a href="exercise-answers.html#cb177-25" tabindex="-1"></a>  <span class="co"># na.rm = TRUE means it does this excluding the missing values</span></span>
<span id="cb177-26"><a href="exercise-answers.html#cb177-26" tabindex="-1"></a></span>
<span id="cb177-27"><a href="exercise-answers.html#cb177-27" tabindex="-1"></a>  <span class="co"># is.na(data_mps$Latitude) identifies any missing latitudes</span></span>
<span id="cb177-28"><a href="exercise-answers.html#cb177-28" tabindex="-1"></a></span>
<span id="cb177-29"><a href="exercise-answers.html#cb177-29" tabindex="-1"></a></span>
<span id="cb177-30"><a href="exercise-answers.html#cb177-30" tabindex="-1"></a>  <span class="co"># Together, this function calculates the average latitude, excluding missing values</span></span>
<span id="cb177-31"><a href="exercise-answers.html#cb177-31" tabindex="-1"></a>  <span class="co"># Assings any missing latitudes the average value.</span></span></code></pre></div>
</div>
<div id="exercise-3.3" class="section level3 unnumbered hasAnchor">
<h3>Exercise 3.3<a href="exercise-answers.html#exercise-3.3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the examples above, in the second example we replaced all missing values with 0. We also replaced any missing latitudes with the average latitude across the dataset in the fourth example. Were these the best imputation choices? What method would you have chosen for dealing with outliers?</p>
<blockquote>
<p>It does not make analytical sense to replace all missing values in the dataset. We have a variety of data formats such as factors including the Crime Type, dates in the format of the Month, as well as character data for location. Each variable should be considered individually to perform the best possible strategy of dealing with NA values.</p>
</blockquote>
<blockquote>
<p>It does not make sense to replace the missing latitudes with the average latitude as this could effect our analysis. Depending on the analysis to be performed and the number of missing values it would be better to drop observations with a missing latitude or set it to a value outside the geographic range of analysis.</p>
</blockquote>
</div>
<div id="exercise-3.4" class="section level3 unnumbered hasAnchor">
<h3>Exercise 3.4<a href="exercise-answers.html#exercise-3.4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The Context column is full of NA values. Can you subset the dataset to remove this column? Can you then filter the dataset to create a new dataframe called data_mps_drugs containing only crimes with the Crime Type recorded as ‘Drugs’.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="exercise-answers.html#cb178-1" tabindex="-1"></a><span class="co">#Load dplyr</span></span>
<span id="cb178-2"><a href="exercise-answers.html#cb178-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:car&#39;:
## 
##     recode</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="exercise-answers.html#cb183-1" tabindex="-1"></a><span class="co">#Using Separate Functions</span></span>
<span id="cb183-2"><a href="exercise-answers.html#cb183-2" tabindex="-1"></a>mps_2024_01_drop <span class="ot">&lt;-</span> <span class="fu">select</span>(mps_2024_01, <span class="sc">-</span>Context)</span>
<span id="cb183-3"><a href="exercise-answers.html#cb183-3" tabindex="-1"></a>mps_2024_01_drugs_1 <span class="ot">&lt;-</span> <span class="fu">filter</span>(mps_2024_01_drop, Crime.type <span class="sc">==</span> <span class="st">&#39;Drugs&#39;</span>)</span>
<span id="cb183-4"><a href="exercise-answers.html#cb183-4" tabindex="-1"></a></span>
<span id="cb183-5"><a href="exercise-answers.html#cb183-5" tabindex="-1"></a><span class="co">#Using a dplyr pipeline</span></span>
<span id="cb183-6"><a href="exercise-answers.html#cb183-6" tabindex="-1"></a>mps_2024_01_drugs_2 <span class="ot">&lt;-</span> mps_2024_01 <span class="sc">%&gt;%</span> </span>
<span id="cb183-7"><a href="exercise-answers.html#cb183-7" tabindex="-1"></a>                        <span class="fu">select</span>(<span class="sc">-</span>Context) <span class="sc">%&gt;%</span> <span class="co">#Drop the &#39;Context&#39; column</span></span>
<span id="cb183-8"><a href="exercise-answers.html#cb183-8" tabindex="-1"></a>                        <span class="fu">filter</span>(Crime.type <span class="sc">==</span> <span class="st">&#39;Drugs&#39;</span>) <span class="co">#Filter Crime Type</span></span></code></pre></div>
</div>
<div id="exercise-3.5" class="section level3 unnumbered hasAnchor">
<h3>Exercise 3.5<a href="exercise-answers.html#exercise-3.5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>How would you merge two datasets if they didn’t have a common key?</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="exercise-answers.html#cb184-1" tabindex="-1"></a><span class="co"># Merge two datasets with different keys</span></span>
<span id="cb184-2"><a href="exercise-answers.html#cb184-2" tabindex="-1"></a>merged_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(data1,</span>
<span id="cb184-3"><a href="exercise-answers.html#cb184-3" tabindex="-1"></a>                     data2,</span>
<span id="cb184-4"><a href="exercise-answers.html#cb184-4" tabindex="-1"></a>                     <span class="at">by.x =</span> <span class="st">&#39;data1_key&#39;</span>,</span>
<span id="cb184-5"><a href="exercise-answers.html#cb184-5" tabindex="-1"></a>                     <span class="at">by.y =</span> <span class="st">&#39;data2.key&#39;</span>)</span></code></pre></div>
</div>
<div id="exercise-3.6" class="section level3 unnumbered hasAnchor">
<h3>Exercise 3.6<a href="exercise-answers.html#exercise-3.6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Using the original data_mps dataframe can you recreate the data_mps_drugs dataframe using the dplyr pipeline operator with the relevant select and filter commands?</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="exercise-answers.html#cb185-1" tabindex="-1"></a><span class="co">#Using a dplyr pipeline to select and filter</span></span>
<span id="cb185-2"><a href="exercise-answers.html#cb185-2" tabindex="-1"></a>mps_2024_01_drugs <span class="ot">&lt;-</span> mps_2024_01 <span class="sc">%&gt;%</span> </span>
<span id="cb185-3"><a href="exercise-answers.html#cb185-3" tabindex="-1"></a>                      <span class="fu">select</span>(<span class="sc">-</span>Context) <span class="sc">%&gt;%</span> <span class="co">#Drop the &#39;Context&#39; column</span></span>
<span id="cb185-4"><a href="exercise-answers.html#cb185-4" tabindex="-1"></a>                      <span class="fu">filter</span>(Crime.type <span class="sc">==</span> <span class="st">&#39;Drugs&#39;</span>) <span class="co">#Filter Crime Type</span></span></code></pre></div>
</div>
<div id="exercise-3.7" class="section level3 unnumbered hasAnchor">
<h3>Exercise 3.7<a href="exercise-answers.html#exercise-3.7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Using the unfiltered data_mps dataset. Convert the Crime Type columns into a factor.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="exercise-answers.html#cb186-1" tabindex="-1"></a><span class="co">#Convert the Crime Type column into a factor.</span></span>
<span id="cb186-2"><a href="exercise-answers.html#cb186-2" tabindex="-1"></a>mps_2024_01<span class="sc">$</span>Crime.type <span class="ot">&lt;-</span> <span class="fu">factor</span>(mps_2024_01<span class="sc">$</span>Crime.type)</span></code></pre></div>
</div>
<div id="exercise-3.8" class="section level3 unnumbered hasAnchor">
<h3>Exercise 3.8<a href="exercise-answers.html#exercise-3.8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Convert the Last Outcome Category to a categorical variable and view a cross-tabulation of the outcomes with the crime types. Which Crime Type has the highest number of Complete Investigations Where No Suspect Was Identified?</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="exercise-answers.html#cb187-1" tabindex="-1"></a><span class="co">#Convert the Last Outcome column into a factor.</span></span>
<span id="cb187-2"><a href="exercise-answers.html#cb187-2" tabindex="-1"></a>mps_2024_01<span class="sc">$</span>Last.outcome.category <span class="ot">&lt;-</span> <span class="fu">factor</span>(mps_2024_01<span class="sc">$</span>Last.outcome.category)</span>
<span id="cb187-3"><a href="exercise-answers.html#cb187-3" tabindex="-1"></a></span>
<span id="cb187-4"><a href="exercise-answers.html#cb187-4" tabindex="-1"></a><span class="co">#Create cross-tabulation</span></span>
<span id="cb187-5"><a href="exercise-answers.html#cb187-5" tabindex="-1"></a><span class="fu">table</span>(mps_2024_01<span class="sc">$</span>Crime.type , mps_2024_01<span class="sc">$</span>Last.outcome.category)</span></code></pre></div>
<pre><code>##                               
##                                      Awaiting court outcome Investigation complete; no suspect identified Local resolution Offender given a caution
##   Anti-social behaviour        16514                      0                                             0                0                        0
##   Bicycle theft                    0                      1                                           672                0                        0
##   Burglary                         0                     61                                          2257                1                        1
##   Criminal damage and arson        0                     78                                          2721               18                       25
##   Drugs                            0                    228                                           318              627                       37
##   Other crime                      0                     36                                           245               28                        3
##   Other theft                      0                     14                                          6252                5                        2
##   Possession of weapons            0                     78                                            52                5                        5
##   Public order                     0                     95                                          1460                7                        3
##   Robbery                          0                     39                                           778                1                        0
##   Shoplifting                      0                    122                                          3375               81                       13
##   Theft from the person            0                     13                                          4296                2                        1
##   Vehicle crime                    0                     20                                          6487                0                        0
##   Violence and sexual offences     0                    454                                          6199               44                       68
##                               
##                                Offender given a drugs possession warning Offender given penalty notice Status update unavailable
##   Anti-social behaviour                                                0                             0                         0
##   Bicycle theft                                                        0                             0                       296
##   Burglary                                                             0                             0                      2762
##   Criminal damage and arson                                            0                             4                      2028
##   Drugs                                                                7                           169                      1327
##   Other crime                                                          0                             0                       519
##   Other theft                                                          0                             0                      4024
##   Possession of weapons                                                0                             0                       269
##   Public order                                                         0                             2                      2592
##   Robbery                                                              0                             0                      2128
##   Shoplifting                                                          0                            19                      1443
##   Theft from the person                                                0                             0                      2603
##   Vehicle crime                                                        0                             0                      2463
##   Violence and sexual offences                                         0                             1                     14913</code></pre>
<blockquote>
<p>The VEHICLE CRIME, crime type has the highest number of Complete Investigations Where No Suspect Was Identified.</p>
</blockquote>
</div>
</div>
<div id="chapter-5" class="section level2 unnumbered hasAnchor">
<h2>Chapter 5<a href="exercise-answers.html#chapter-5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="exercise-5.1" class="section level3 unnumbered hasAnchor">
<h3>Exercise 5.1<a href="exercise-answers.html#exercise-5.1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Download the police_activity_data.csv file and load it into a R data frame. Produce a basic summary of the Response Time variable. What does the difference between the Mean and Median measure tell you about the skewness of the data?</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="exercise-answers.html#cb189-1" tabindex="-1"></a><span class="co">#Load data</span></span>
<span id="cb189-2"><a href="exercise-answers.html#cb189-2" tabindex="-1"></a>police_activity_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;data/police_activity_data.csv&#39;</span>)</span>
<span id="cb189-3"><a href="exercise-answers.html#cb189-3" tabindex="-1"></a></span>
<span id="cb189-4"><a href="exercise-answers.html#cb189-4" tabindex="-1"></a><span class="co">#Summary of Response Time Variable</span></span>
<span id="cb189-5"><a href="exercise-answers.html#cb189-5" tabindex="-1"></a><span class="fu">summary</span>(police_activity_data<span class="sc">$</span>ResponseTime)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    5.00    9.00   13.00   12.42   16.00   20.00</code></pre>
<blockquote>
<p>The Mean (12.42) is SMALLER than the Median (13.00). When the mean of a dataset is smaller than the median, it generally indicates that the data distribution is left-skewed (or negatively skewed). In a left-skewed distribution, the tail on the left side of the distribution is longer than the tail on the right side. This means there are a few low values that pull the mean down, while the majority of the data are higher, which positions the median closer to the upper range of the data.</p>
</blockquote>
</div>
<div id="excercise-5.2" class="section level3 unnumbered hasAnchor">
<h3>Excercise 5.2<a href="exercise-answers.html#excercise-5.2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Create a Bar Chart of the Borough variable in the police_activity_data dataset. Which borough has the greatest number of crimes?</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="exercise-answers.html#cb191-1" tabindex="-1"></a><span class="co">#Load the ggplot2 library</span></span>
<span id="cb191-2"><a href="exercise-answers.html#cb191-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb191-3"><a href="exercise-answers.html#cb191-3" tabindex="-1"></a></span>
<span id="cb191-4"><a href="exercise-answers.html#cb191-4" tabindex="-1"></a><span class="co"># Bar chart for a categorical variable</span></span>
<span id="cb191-5"><a href="exercise-answers.html#cb191-5" tabindex="-1"></a><span class="fu">ggplot</span>(police_activity_data, <span class="fu">aes</span>(<span class="at">x =</span> Borough)) <span class="sc">+</span></span>
<span id="cb191-6"><a href="exercise-answers.html#cb191-6" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb191-7"><a href="exercise-answers.html#cb191-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Bar Chart Displaying the Number of Incidents in Each Borough in August 2024&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Borough&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Number of Incidents&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-134-1.png" width="672" />
&gt; The NORTH borough had the most incidents in the period in question.</p>
</div>
<div id="exercise-5.3" class="section level3 unnumbered hasAnchor">
<h3>Exercise 5.3<a href="exercise-answers.html#exercise-5.3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Create a Histogram of the ResponseTime variable in the police_activity_data dataset setting the bin size to 4. How is the response time distributed?</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="exercise-answers.html#cb192-1" tabindex="-1"></a><span class="fu">ggplot</span>(police_activity_data, <span class="fu">aes</span>(<span class="at">x =</span> ResponseTime)) <span class="sc">+</span></span>
<span id="cb192-2"><a href="exercise-answers.html#cb192-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">4</span>, <span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb192-3"><a href="exercise-answers.html#cb192-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Histogram of Response Time&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Response Time (Minutes)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Frequency&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-135-1.png" width="672" /></p>
<blockquote>
<p>The histogram shows the distribution of response times, with most values concentrated between 8 and 16 minutes. The distribution appears roughly normal, with no strong skewness, indicating a fairly even spread of response times across this range. The tails on both sides are shorter, suggesting fewer instances of very short (less than 5 minutes) or very long (more than 20 minutes) response times.</p>
</blockquote>
</div>
<div id="exercise-5.4" class="section level3 unnumbered hasAnchor">
<h3>Exercise 5.4<a href="exercise-answers.html#exercise-5.4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Create a Boxplot of the ResponseTime variable for each of the Borough in the police_activity_data dataset. Which Borough has the lowest Median response time? Which Borough has the smallest range of response times?</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="exercise-answers.html#cb193-1" tabindex="-1"></a><span class="fu">ggplot</span>(police_activity_data, <span class="fu">aes</span>(<span class="at">x =</span> Borough, <span class="at">y =</span> ResponseTime)) <span class="sc">+</span></span>
<span id="cb193-2"><a href="exercise-answers.html#cb193-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb193-3"><a href="exercise-answers.html#cb193-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Boxplot of Response Time by Borough&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Borough&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Response Time&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-136-1.png" width="672" />
&gt; The EAST borough has the lowest MEDIAN RESPONSE TIME.
&gt; The WEST borough had the smallest RANGE OF RESPONSE TIMES.</p>
</div>
<div id="exercise-5.6" class="section level3 unnumbered hasAnchor">
<h3>Exercise 5.6<a href="exercise-answers.html#exercise-5.6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Using your Boxplot Diagram of the ResponseTime variable for each of the Borough in the police_activity_data dataset. Add some colour!</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="exercise-answers.html#cb194-1" tabindex="-1"></a><span class="fu">ggplot</span>(police_activity_data, <span class="fu">aes</span>(<span class="at">x =</span> Borough, <span class="at">y =</span> ResponseTime, <span class="at">fill =</span> Borough)) <span class="sc">+</span></span>
<span id="cb194-2"><a href="exercise-answers.html#cb194-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb194-3"><a href="exercise-answers.html#cb194-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Boxplot of Response Time by Borough&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Borough&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Response Time&quot;</span>) <span class="sc">+</span></span>
<span id="cb194-4"><a href="exercise-answers.html#cb194-4" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Pastel1&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-137-1.png" width="672" /></p>
</div>
<div id="exercise-5.7" class="section level3 unnumbered hasAnchor">
<h3>Exercise 5.7<a href="exercise-answers.html#exercise-5.7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Using the police_activity_data dataset, calculate the mean and standard deviation of the ResponseTime based on the IncidentType. Which Incident Type had the greatest mean response time?</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="exercise-answers.html#cb195-1" tabindex="-1"></a><span class="co"># Load the dplyr library</span></span>
<span id="cb195-2"><a href="exercise-answers.html#cb195-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb195-3"><a href="exercise-answers.html#cb195-3" tabindex="-1"></a></span>
<span id="cb195-4"><a href="exercise-answers.html#cb195-4" tabindex="-1"></a><span class="co"># Summarise data: mean and standard deviation by group</span></span>
<span id="cb195-5"><a href="exercise-answers.html#cb195-5" tabindex="-1"></a>police_activity_data_summary <span class="ot">&lt;-</span> police_activity_data <span class="sc">%&gt;%</span></span>
<span id="cb195-6"><a href="exercise-answers.html#cb195-6" tabindex="-1"></a>                                  <span class="fu">group_by</span>(IncidentType) <span class="sc">%&gt;%</span></span>
<span id="cb195-7"><a href="exercise-answers.html#cb195-7" tabindex="-1"></a>                                  <span class="fu">summarize</span>(</span>
<span id="cb195-8"><a href="exercise-answers.html#cb195-8" tabindex="-1"></a>                                    <span class="at">mean_value =</span> <span class="fu">mean</span>(ResponseTime, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb195-9"><a href="exercise-answers.html#cb195-9" tabindex="-1"></a>                                    <span class="at">sd_value =</span> <span class="fu">sd</span>(ResponseTime, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb195-10"><a href="exercise-answers.html#cb195-10" tabindex="-1"></a>                                  )</span>
<span id="cb195-11"><a href="exercise-answers.html#cb195-11" tabindex="-1"></a></span>
<span id="cb195-12"><a href="exercise-answers.html#cb195-12" tabindex="-1"></a><span class="co">#Print results</span></span>
<span id="cb195-13"><a href="exercise-answers.html#cb195-13" tabindex="-1"></a><span class="fu">print</span>(police_activity_data_summary)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   IncidentType       mean_value sd_value
##   &lt;chr&gt;                   &lt;dbl&gt;    &lt;dbl&gt;
## 1 Assault                  11.8     4.14
## 2 Burglary                 12.2     4.30
## 3 Public Disturbance       11.3     4.12
## 4 Robbery                  13.4     4.07
## 5 Traffic Stop             13.4     4.58</code></pre>
<blockquote>
<p>ROBBERY had the GREATEST MEAN RESPONSE TIME.</p>
</blockquote>
</div>
<div id="exercise-5.8" class="section level3 unnumbered hasAnchor">
<h3>Exercise 5.8<a href="exercise-answers.html#exercise-5.8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Building on the previous exercise, create a plot of the mean ResponseTime based on the IncidentType. The factors along the x-axis should be sorted alphabetically. Can you try sorting these in ascending order of their mean?</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="exercise-answers.html#cb197-1" tabindex="-1"></a><span class="fu">ggplot</span>(police_activity_data_summary, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(IncidentType, mean_value), <span class="at">y =</span> mean_value)) <span class="sc">+</span></span>
<span id="cb197-2"><a href="exercise-answers.html#cb197-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb197-3"><a href="exercise-answers.html#cb197-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Mean Response Time by Incident Type&quot;</span>,</span>
<span id="cb197-4"><a href="exercise-answers.html#cb197-4" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Incident Type&quot;</span>,</span>
<span id="cb197-5"><a href="exercise-answers.html#cb197-5" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Mean Response Time&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-139-1.png" width="672" /></p>
</div>
<div id="excerise-5.9" class="section level3 unnumbered hasAnchor">
<h3>Excerise 5.9<a href="exercise-answers.html#excerise-5.9" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Use the facet wrap functionality to create a series of histograms representing the IncidentSeverity across the four different boroughs using a binwidth of 3. How does the response time vary across the four different boroughs?</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="exercise-answers.html#cb198-1" tabindex="-1"></a><span class="fu">ggplot</span>(police_activity_data, <span class="fu">aes</span>(<span class="at">x =</span> IncidentSeverity)) <span class="sc">+</span></span>
<span id="cb198-2"><a href="exercise-answers.html#cb198-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb198-3"><a href="exercise-answers.html#cb198-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Borough) <span class="sc">+</span></span>
<span id="cb198-4"><a href="exercise-answers.html#cb198-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Histogram of Incident Severity Faceted by Borough&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-140-1.png" width="672" /></p>
<blockquote>
<p>The distribution of incident severity is fairly consistent across all boroughs, with most incidents falling within the mid-range of severity on the severity scale.</p>
</blockquote>
</div>
<div id="exercise-5.10" class="section level3 unnumbered hasAnchor">
<h3>Exercise 5.10<a href="exercise-answers.html#exercise-5.10" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Using dplyr produce a count of the number of crimes that occurred on each day. Use this information to create a scatterplot with a regression line. What do you notice about the trend?</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="exercise-answers.html#cb199-1" tabindex="-1"></a>summary_data <span class="ot">&lt;-</span> police_activity_data <span class="sc">%&gt;%</span></span>
<span id="cb199-2"><a href="exercise-answers.html#cb199-2" tabindex="-1"></a>                  <span class="fu">group_by</span>(Date) <span class="sc">%&gt;%</span>   <span class="co"># Group by the &#39;Date&#39; column</span></span>
<span id="cb199-3"><a href="exercise-answers.html#cb199-3" tabindex="-1"></a>                  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="co"># Produce a Count</span></span>
<span id="cb199-4"><a href="exercise-answers.html#cb199-4" tabindex="-1"></a></span>
<span id="cb199-5"><a href="exercise-answers.html#cb199-5" tabindex="-1"></a><span class="fu">ggplot</span>(summary_data , <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.Date</span>(Date), <span class="at">y =</span> count)) <span class="sc">+</span></span>
<span id="cb199-6"><a href="exercise-answers.html#cb199-6" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb199-7"><a href="exercise-answers.html#cb199-7" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb199-8"><a href="exercise-answers.html#cb199-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Scatter Plot of Number of Crimes Across August 2024 with Regression Line&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Number of Crimes&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-141-1.png" width="672" /></p>
</div>
</div>
<div id="chapter-6" class="section level2 unnumbered hasAnchor">
<h2>Chapter 6<a href="exercise-answers.html#chapter-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You have a dataset from a national survey on perceptions of crime. This dataset provides a comprehensive analysis of crime and policing by examining crime types, victim demographics, police responses, community engagement, and socioeconomic factors to understand the respondents crime experiences and perceptions. Download the Crime Survey Data (SPSS Format) and perform a descriptive analysis of the data. The steps you need to follow are listed below to help you.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="exercise-answers.html#cb201-1" tabindex="-1"></a><span class="co">#Load haven library</span></span>
<span id="cb201-2"><a href="exercise-answers.html#cb201-2" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb201-3"><a href="exercise-answers.html#cb201-3" tabindex="-1"></a></span>
<span id="cb201-4"><a href="exercise-answers.html#cb201-4" tabindex="-1"></a><span class="co">#load Survey library</span></span>
<span id="cb201-5"><a href="exercise-answers.html#cb201-5" tabindex="-1"></a><span class="fu">library</span>(survey)</span></code></pre></div>
<pre><code>## Loading required package: grid</code></pre>
<pre><code>## Loading required package: survival</code></pre>
<pre><code>## 
## Attaching package: &#39;survival&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:caret&#39;:
## 
##     cluster</code></pre>
<pre><code>## 
## Attaching package: &#39;survey&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:graphics&#39;:
## 
##     dotchart</code></pre>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="exercise-answers.html#cb208-1" tabindex="-1"></a><span class="co">#Load the dataset</span></span>
<span id="cb208-2"><a href="exercise-answers.html#cb208-2" tabindex="-1"></a>survey_data <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">&quot;data/crime_survey_data.sav&quot;</span>)</span>
<span id="cb208-3"><a href="exercise-answers.html#cb208-3" tabindex="-1"></a></span>
<span id="cb208-4"><a href="exercise-answers.html#cb208-4" tabindex="-1"></a><span class="co">#View loaded data</span></span>
<span id="cb208-5"><a href="exercise-answers.html#cb208-5" tabindex="-1"></a><span class="fu">head</span>(survey_data)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 21
##      id region crime_type satisfaction programs gender incident_severity response_time victim_age victim_gender victim_ethnicity police_action community_engagement
##   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;             &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;                     &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;         &lt;chr&gt;            &lt;chr&gt;                        &lt;dbl&gt;
## 1     1 East   Assault               5        1 Male   Serious                       8 55+        Other         Asian            Warning                          3
## 2     2 East   Vandalism             2        6 Female Minor                        91 18-24      Female        Asian            Arrest                           2
## 3     3 East   Vandalism             3        3 Male   Moderate                     18 18-24      Other         Hispanic         Investigation                    1
## 4     4 South  Assault               1        5 Male   Serious                     120 18-24      Other         Asian            Investigation                    1
## 5     5 East   Theft                 5        1 Female Minor                        15 18-24      Female        Black            Arrest                           1
## 6     6 South  Theft                 3        6 Female Minor                        55 Under 18   Female        Black            Warning                          4
## # ℹ 8 more variables: perceived_crime_rate &lt;chr&gt;, education &lt;chr&gt;, employment_status &lt;chr&gt;, household_income &lt;chr&gt;, living_situation &lt;chr&gt;, previous_victimization &lt;chr&gt;,
## #   neighborhood_safety &lt;dbl&gt;, weight &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="exercise-answers.html#cb210-1" tabindex="-1"></a><span class="co">#Create a survey design object</span></span>
<span id="cb210-2"><a href="exercise-answers.html#cb210-2" tabindex="-1"></a>survey_design <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(</span>
<span id="cb210-3"><a href="exercise-answers.html#cb210-3" tabindex="-1"></a>  <span class="at">id =</span> <span class="sc">~</span>id,</span>
<span id="cb210-4"><a href="exercise-answers.html#cb210-4" tabindex="-1"></a>  <span class="at">weights =</span> <span class="sc">~</span>weight,</span>
<span id="cb210-5"><a href="exercise-answers.html#cb210-5" tabindex="-1"></a>  <span class="at">data =</span> survey_data</span>
<span id="cb210-6"><a href="exercise-answers.html#cb210-6" tabindex="-1"></a>)</span>
<span id="cb210-7"><a href="exercise-answers.html#cb210-7" tabindex="-1"></a></span>
<span id="cb210-8"><a href="exercise-answers.html#cb210-8" tabindex="-1"></a><span class="co">#Create a frequency distribution of the crime_type</span></span>
<span id="cb210-9"><a href="exercise-answers.html#cb210-9" tabindex="-1"></a><span class="fu">svytable</span>(<span class="sc">~</span>crime_type, <span class="at">design =</span> survey_design)</span></code></pre></div>
<pre><code>## crime_type
##   Assault  Burglary     Theft Vandalism 
##  146.0768  142.8698  161.8578  172.4434</code></pre>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="exercise-answers.html#cb212-1" tabindex="-1"></a><span class="co"># and gender variable.</span></span>
<span id="cb212-2"><a href="exercise-answers.html#cb212-2" tabindex="-1"></a><span class="fu">svytable</span>(<span class="sc">~</span>gender, <span class="at">design =</span> survey_design)</span></code></pre></div>
<pre><code>## gender
##   Female     Male 
## 284.1523 339.0955</code></pre>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="exercise-answers.html#cb214-1" tabindex="-1"></a><span class="co"># Load the janitor package</span></span>
<span id="cb214-2"><a href="exercise-answers.html#cb214-2" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;janitor&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     chisq.test, fisher.test</code></pre>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="exercise-answers.html#cb217-1" tabindex="-1"></a><span class="co">#Cross-tabulate crime_type by region and gender (separately and together) to see the distribution across different regions and genders.</span></span>
<span id="cb217-2"><a href="exercise-answers.html#cb217-2" tabindex="-1"></a></span>
<span id="cb217-3"><a href="exercise-answers.html#cb217-3" tabindex="-1"></a><span class="co"># Cross-tabulation with janitor: Crime Type &amp; Region</span></span>
<span id="cb217-4"><a href="exercise-answers.html#cb217-4" tabindex="-1"></a>crime_region_tab <span class="ot">&lt;-</span> <span class="fu">svytable</span>(<span class="sc">~</span>crime_type <span class="sc">+</span> region, survey_design)</span>
<span id="cb217-5"><a href="exercise-answers.html#cb217-5" tabindex="-1"></a></span>
<span id="cb217-6"><a href="exercise-answers.html#cb217-6" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb217-7"><a href="exercise-answers.html#cb217-7" tabindex="-1"></a><span class="fu">print</span>(crime_region_tab)</span></code></pre></div>
<pre><code>##            region
## crime_type      East    North    South     West
##   Assault   38.00701 37.61599 32.31634 38.13746
##   Burglary  26.63030 45.57457 47.72543 22.93950
##   Theft     34.02101 50.79713 45.24576 31.79386
##   Vandalism 51.57803 46.30077 42.95608 31.60851</code></pre>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="exercise-answers.html#cb219-1" tabindex="-1"></a><span class="co"># Cross-tabulation with janitor: Crime Type &amp; Gender</span></span>
<span id="cb219-2"><a href="exercise-answers.html#cb219-2" tabindex="-1"></a>crime_gender_tab <span class="ot">&lt;-</span> <span class="fu">svytable</span>(<span class="sc">~</span>crime_type <span class="sc">+</span> gender, survey_design)</span>
<span id="cb219-3"><a href="exercise-answers.html#cb219-3" tabindex="-1"></a></span>
<span id="cb219-4"><a href="exercise-answers.html#cb219-4" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb219-5"><a href="exercise-answers.html#cb219-5" tabindex="-1"></a><span class="fu">print</span>(crime_region_tab)</span></code></pre></div>
<pre><code>##            region
## crime_type      East    North    South     West
##   Assault   38.00701 37.61599 32.31634 38.13746
##   Burglary  26.63030 45.57457 47.72543 22.93950
##   Theft     34.02101 50.79713 45.24576 31.79386
##   Vandalism 51.57803 46.30077 42.95608 31.60851</code></pre>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="exercise-answers.html#cb221-1" tabindex="-1"></a><span class="do">## Cross-tabulation with survey: Crime Type &amp; Region + Gender</span></span>
<span id="cb221-2"><a href="exercise-answers.html#cb221-2" tabindex="-1"></a>crime_region_gender_tab <span class="ot">&lt;-</span> <span class="fu">svytable</span>(<span class="sc">~</span>crime_type <span class="sc">+</span> region <span class="sc">+</span> gender, survey_design)</span>
<span id="cb221-3"><a href="exercise-answers.html#cb221-3" tabindex="-1"></a></span>
<span id="cb221-4"><a href="exercise-answers.html#cb221-4" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb221-5"><a href="exercise-answers.html#cb221-5" tabindex="-1"></a><span class="fu">print</span>(crime_region_gender_tab)</span></code></pre></div>
<pre><code>## , , gender = Female
## 
##            region
## crime_type      East    North    South     West
##   Assault   16.89515 11.89451 17.06074 17.06962
##   Burglary  12.62156 24.57370 18.88147 11.25734
##   Theft     13.91476 24.26910 24.08906 15.52493
##   Vandalism 27.34231 23.79401 10.02678 14.93727
## 
## , , gender = Male
## 
##            region
## crime_type      East    North    South     West
##   Assault   21.11187 25.72148 15.25560 21.06784
##   Burglary  14.00874 21.00087 28.84396 11.68215
##   Theft     20.10625 26.52803 21.15670 16.26893
##   Vandalism 24.23571 22.50676 32.92930 16.67125</code></pre>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="exercise-answers.html#cb223-1" tabindex="-1"></a><span class="co">#Create a new variable to categorise satisfaction into high and low satisfaction (above 3 = High, 3 or below = Low).</span></span>
<span id="cb223-2"><a href="exercise-answers.html#cb223-2" tabindex="-1"></a>survey_data <span class="ot">&lt;-</span> survey_data <span class="sc">%&gt;%</span></span>
<span id="cb223-3"><a href="exercise-answers.html#cb223-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">satisfaction_rank =</span> <span class="fu">ifelse</span>(satisfaction <span class="sc">&gt;</span> <span class="dv">3</span>, <span class="st">&quot;High&quot;</span>, <span class="st">&quot;Low&quot;</span>))</span>
<span id="cb223-4"><a href="exercise-answers.html#cb223-4" tabindex="-1"></a></span>
<span id="cb223-5"><a href="exercise-answers.html#cb223-5" tabindex="-1"></a><span class="co">#Output check</span></span>
<span id="cb223-6"><a href="exercise-answers.html#cb223-6" tabindex="-1"></a><span class="fu">head</span>(survey_data)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 22
##      id region crime_type satisfaction programs gender incident_severity response_time victim_age victim_gender victim_ethnicity police_action community_engagement
##   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;             &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;                     &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;         &lt;chr&gt;            &lt;chr&gt;                        &lt;dbl&gt;
## 1     1 East   Assault               5        1 Male   Serious                       8 55+        Other         Asian            Warning                          3
## 2     2 East   Vandalism             2        6 Female Minor                        91 18-24      Female        Asian            Arrest                           2
## 3     3 East   Vandalism             3        3 Male   Moderate                     18 18-24      Other         Hispanic         Investigation                    1
## 4     4 South  Assault               1        5 Male   Serious                     120 18-24      Other         Asian            Investigation                    1
## 5     5 East   Theft                 5        1 Female Minor                        15 18-24      Female        Black            Arrest                           1
## 6     6 South  Theft                 3        6 Female Minor                        55 Under 18   Female        Black            Warning                          4
## # ℹ 9 more variables: perceived_crime_rate &lt;chr&gt;, education &lt;chr&gt;, employment_status &lt;chr&gt;, household_income &lt;chr&gt;, living_situation &lt;chr&gt;, previous_victimization &lt;chr&gt;,
## #   neighborhood_safety &lt;dbl&gt;, weight &lt;dbl&gt;, satisfaction_rank &lt;chr&gt;</code></pre>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="exercise-answers.html#cb225-1" tabindex="-1"></a><span class="co">#Update the survey design with the new variable.</span></span>
<span id="cb225-2"><a href="exercise-answers.html#cb225-2" tabindex="-1"></a>survey_design_updated <span class="ot">&lt;-</span> <span class="fu">update</span>(survey_design,</span>
<span id="cb225-3"><a href="exercise-answers.html#cb225-3" tabindex="-1"></a>                                <span class="at">satisfaction_rank =</span> survey_data<span class="sc">$</span>satisfaction_rank)</span>
<span id="cb225-4"><a href="exercise-answers.html#cb225-4" tabindex="-1"></a></span>
<span id="cb225-5"><a href="exercise-answers.html#cb225-5" tabindex="-1"></a></span>
<span id="cb225-6"><a href="exercise-answers.html#cb225-6" tabindex="-1"></a><span class="co"># Mean number of community programs by satisfaction level</span></span>
<span id="cb225-7"><a href="exercise-answers.html#cb225-7" tabindex="-1"></a>mean_programs_satisfaction <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="sc">~</span>programs, <span class="sc">~</span>satisfaction_rank, survey_design_updated, svymean)</span>
<span id="cb225-8"><a href="exercise-answers.html#cb225-8" tabindex="-1"></a></span>
<span id="cb225-9"><a href="exercise-answers.html#cb225-9" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb225-10"><a href="exercise-answers.html#cb225-10" tabindex="-1"></a><span class="fu">print</span>(mean_programs_satisfaction)</span></code></pre></div>
<pre><code>##      satisfaction_rank programs        se
## High              High 5.536490 0.2209763
## Low                Low 5.665286 0.1801161</code></pre>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="exercise-answers.html#cb227-1" tabindex="-1"></a><span class="co"># Mean number of community programs by gender</span></span>
<span id="cb227-2"><a href="exercise-answers.html#cb227-2" tabindex="-1"></a>mean_programs_gender <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="sc">~</span>programs, <span class="sc">~</span>gender, survey_design_updated, svymean)</span>
<span id="cb227-3"><a href="exercise-answers.html#cb227-3" tabindex="-1"></a></span>
<span id="cb227-4"><a href="exercise-answers.html#cb227-4" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb227-5"><a href="exercise-answers.html#cb227-5" tabindex="-1"></a><span class="fu">print</span>(mean_programs_gender)</span></code></pre></div>
<pre><code>##        gender programs        se
## Female Female 5.423680 0.2140237
## Male     Male 5.774012 0.1823737</code></pre>
</div>
<div id="chapter-7" class="section level2 unnumbered hasAnchor">
<h2>Chapter 7<a href="exercise-answers.html#chapter-7" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="exercise-7.1" class="section level3 unnumbered hasAnchor">
<h3>Exercise 7.1<a href="exercise-answers.html#exercise-7.1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The Metropolitan Police Service have implemented a new strategy to target Violence Against Women and Girls in 6 wards. The number of incidents in March across these 6 wards was 100, 102, 104, 106, and 108. After the implementation of the new strategy the number of incidents in April across these 6 wards was 110, 111, 115, 117, 120 respectively. Has the new strategy had an impact on the number of incidents?</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="exercise-answers.html#cb229-1" tabindex="-1"></a><span class="co">#Input the pre-treatment values</span></span>
<span id="cb229-2"><a href="exercise-answers.html#cb229-2" tabindex="-1"></a>pre_treatment <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">102</span>, <span class="dv">104</span>, <span class="dv">106</span>, <span class="dv">108</span>)</span>
<span id="cb229-3"><a href="exercise-answers.html#cb229-3" tabindex="-1"></a><span class="co">#Input the post-treatment values</span></span>
<span id="cb229-4"><a href="exercise-answers.html#cb229-4" tabindex="-1"></a>post_treatment <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">110</span>, <span class="dv">111</span>, <span class="dv">115</span>, <span class="dv">117</span>, <span class="dv">120</span>)</span>
<span id="cb229-5"><a href="exercise-answers.html#cb229-5" tabindex="-1"></a></span>
<span id="cb229-6"><a href="exercise-answers.html#cb229-6" tabindex="-1"></a><span class="fu">t.test</span>(pre_treatment, post_treatment, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  pre_treatment and post_treatment
## t = -20.788, df = 4, p-value = 3.164e-05
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -12.015715  -9.184285
## sample estimates:
## mean difference 
##           -10.6</code></pre>
<blockquote>
<p>The p-value is smaller than 0.05 indicating statistical significance. A significant result indicates that the mean difference between the pre-treatment and post-treatment measures is unlikely to have occurred by chance. In other words, the treatment (or intervention) has had a measurable effect on the outcome variable.</p>
</blockquote>
</div>
<div id="exercise-7.2" class="section level3 unnumbered hasAnchor">
<h3>Exercise 7.2<a href="exercise-answers.html#exercise-7.2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>You want to identify if the number of Stop and Search performed in the month of September across 6 Boroughs where the Stop and Search occurred is Uniformly distributed. Use the following data to identify if the Number of Stop and Search performed is uniform across the 6 Boroughs.</p>
<p>Richmond: 36 // Kingston: 25 // Merton: 28 // Sutton: 34 // Croydon: 42 // Wandsworth: 32</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="exercise-answers.html#cb231-1" tabindex="-1"></a><span class="co">#Observed frequencies of Stop &amp; Search</span></span>
<span id="cb231-2"><a href="exercise-answers.html#cb231-2" tabindex="-1"></a>observed_frequencies <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">35</span>, <span class="dv">25</span>, <span class="dv">28</span>, <span class="dv">34</span>, <span class="dv">42</span>, <span class="dv">32</span>)</span>
<span id="cb231-3"><a href="exercise-answers.html#cb231-3" tabindex="-1"></a></span>
<span id="cb231-4"><a href="exercise-answers.html#cb231-4" tabindex="-1"></a><span class="co"># Expected frequencies under the null hypothesis (uniform distribution)</span></span>
<span id="cb231-5"><a href="exercise-answers.html#cb231-5" tabindex="-1"></a>expected_frequencies <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">sum</span>(observed_frequencies) <span class="sc">/</span> <span class="fu">length</span>(observed_frequencies), <span class="fu">length</span>(observed_frequencies))</span>
<span id="cb231-6"><a href="exercise-answers.html#cb231-6" tabindex="-1"></a></span>
<span id="cb231-7"><a href="exercise-answers.html#cb231-7" tabindex="-1"></a><span class="co"># Perform the Chi-Square Goodness-of-Fit Test</span></span>
<span id="cb231-8"><a href="exercise-answers.html#cb231-8" tabindex="-1"></a>chisq_test_goodness_of_fit <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(observed_frequencies, <span class="at">p =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">/</span><span class="fu">length</span>(observed_frequencies), <span class="fu">length</span>(observed_frequencies)))</span>
<span id="cb231-9"><a href="exercise-answers.html#cb231-9" tabindex="-1"></a></span>
<span id="cb231-10"><a href="exercise-answers.html#cb231-10" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb231-11"><a href="exercise-answers.html#cb231-11" tabindex="-1"></a><span class="fu">print</span>(chisq_test_goodness_of_fit)</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  observed_frequencies
## X-squared = 5.3673, df = 5, p-value = 0.3727</code></pre>
<blockquote>
<p>The p-value represents the probability of observing the data, or something more extreme, assuming that the null hypothesis is true. A p-value greater than 0.05 indicates that there is not enough evidence to reject the null hypothesis at the 5% significance level. In other words, the observed data does not significantly deviate from what would be expected under the null hypothesis.</p>
</blockquote>
</div>
<div id="exercise-7.3" class="section level3 unnumbered hasAnchor">
<h3>Exercise 7.3<a href="exercise-answers.html#exercise-7.3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Local residents in 3 boroughs were asked to rate their confidence in the Metropolitan Police Service rating their scores from 0 to 10. The average score across a 3 month period is as follows.</p>
<p>Kingston : 7.0, 7.5, 8.2
Richmond : 8.3, 6.4, 7.9
Sutton : 6.4, 4.5, 5.8</p>
<p>Does the mean confidence level across the 3 month preiod differ between the three boroughs?</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="exercise-answers.html#cb233-1" tabindex="-1"></a><span class="co"># One-way ANOVA</span></span>
<span id="cb233-2"><a href="exercise-answers.html#cb233-2" tabindex="-1"></a><span class="co"># Comparing scores across three different groups</span></span>
<span id="cb233-3"><a href="exercise-answers.html#cb233-3" tabindex="-1"></a></span>
<span id="cb233-4"><a href="exercise-answers.html#cb233-4" tabindex="-1"></a>kingston <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">7.0</span>, <span class="fl">7.5</span>, <span class="fl">8.2</span>)</span>
<span id="cb233-5"><a href="exercise-answers.html#cb233-5" tabindex="-1"></a>richmond <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">8.3</span>, <span class="fl">6.4</span>, <span class="fl">7.9</span>)</span>
<span id="cb233-6"><a href="exercise-answers.html#cb233-6" tabindex="-1"></a>sutton   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">6.4</span>, <span class="fl">4.5</span>, <span class="fl">5.8</span>)</span>
<span id="cb233-7"><a href="exercise-answers.html#cb233-7" tabindex="-1"></a></span>
<span id="cb233-8"><a href="exercise-answers.html#cb233-8" tabindex="-1"></a><span class="co">#Convert to dataframe</span></span>
<span id="cb233-9"><a href="exercise-answers.html#cb233-9" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb233-10"><a href="exercise-answers.html#cb233-10" tabindex="-1"></a>  <span class="at">score =</span> <span class="fu">c</span>(kingston, richmond, sutton),</span>
<span id="cb233-11"><a href="exercise-answers.html#cb233-11" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">each =</span> <span class="dv">3</span>))</span>
<span id="cb233-12"><a href="exercise-answers.html#cb233-12" tabindex="-1"></a>)</span>
<span id="cb233-13"><a href="exercise-answers.html#cb233-13" tabindex="-1"></a></span>
<span id="cb233-14"><a href="exercise-answers.html#cb233-14" tabindex="-1"></a><span class="co">#Run anova</span></span>
<span id="cb233-15"><a href="exercise-answers.html#cb233-15" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(score <span class="sc">~</span> group, <span class="at">data =</span> data)</span>
<span id="cb233-16"><a href="exercise-answers.html#cb233-16" tabindex="-1"></a></span>
<span id="cb233-17"><a href="exercise-answers.html#cb233-17" tabindex="-1"></a><span class="co">#Print result</span></span>
<span id="cb233-18"><a href="exercise-answers.html#cb233-18" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## group        2  7.869   3.934    5.11 0.0506 .
## Residuals    6  4.620   0.770                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<blockquote>
<p>F-value: This is the ratio of the Mean Square for the group to the Mean Square for the residuals. It tests whether the variability between groups is significantly greater than the variability within groups. The F-value of 5.11 suggests that there is some evidence that the means of the groups differ.</p>
</blockquote>
<blockquote>
<p>p-value: This p-value tells us the probability of observing an F-value as extreme as 5.11, assuming the null hypothesis is true (i.e., assuming there is no difference between group means). A p-value of 0.0506 is just above the commonly used significance level of 0.05.</p>
</blockquote>
<blockquote>
<p>The null hypothesis for ANOVA is that all group means are equal (i.e., there is no significant difference between the means of the groups). The result suggests that there is some evidence to reject the null hypothesis, but it is not strong enough to meet the conventional significance level of 0.05.</p>
</blockquote>
</div>
<div id="exercise-7.4" class="section level3 unnumbered hasAnchor">
<h3>Exercise 7.4<a href="exercise-answers.html#exercise-7.4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>You have data on the number of community outreach programs conducted in 6 boroughs as well as the associated crime rates. You want to determine if there’s a linear relationship between these two variables. Use the data below to perform a correlation analysis.</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="exercise-answers.html#cb235-1" tabindex="-1"></a><span class="co">#Create dataframe</span></span>
<span id="cb235-2"><a href="exercise-answers.html#cb235-2" tabindex="-1"></a>data_outreach <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb235-3"><a href="exercise-answers.html#cb235-3" tabindex="-1"></a>  <span class="at">num_crimes =</span> <span class="fu">c</span>(<span class="dv">145</span>, <span class="dv">154</span>, <span class="dv">218</span>, <span class="dv">255</span>, <span class="dv">234</span>, <span class="dv">189</span>),</span>
<span id="cb235-4"><a href="exercise-answers.html#cb235-4" tabindex="-1"></a>  <span class="at">community_prog =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">19</span>, <span class="dv">17</span>, <span class="dv">15</span>)</span>
<span id="cb235-5"><a href="exercise-answers.html#cb235-5" tabindex="-1"></a>)</span>
<span id="cb235-6"><a href="exercise-answers.html#cb235-6" tabindex="-1"></a></span>
<span id="cb235-7"><a href="exercise-answers.html#cb235-7" tabindex="-1"></a><span class="co"># View the dataset</span></span>
<span id="cb235-8"><a href="exercise-answers.html#cb235-8" tabindex="-1"></a><span class="fu">print</span>(data_outreach)</span></code></pre></div>
<pre><code>##   num_crimes community_prog
## 1        145              4
## 2        154              5
## 3        218              8
## 4        255             19
## 5        234             17
## 6        189             15</code></pre>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="exercise-answers.html#cb237-1" tabindex="-1"></a><span class="co">#Run pearson correlation</span></span>
<span id="cb237-2"><a href="exercise-answers.html#cb237-2" tabindex="-1"></a><span class="fu">cor</span>(data_outreach<span class="sc">$</span>num_crimes, data_outreach<span class="sc">$</span>community_prog)</span></code></pre></div>
<pre><code>## [1] 0.8454724</code></pre>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="exercise-answers.html#cb239-1" tabindex="-1"></a><span class="co"># Creating and visualizing a correlation matrix</span></span>
<span id="cb239-2"><a href="exercise-answers.html#cb239-2" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb239-3"><a href="exercise-answers.html#cb239-3" tabindex="-1"></a></span>
<span id="cb239-4"><a href="exercise-answers.html#cb239-4" tabindex="-1"></a><span class="co"># Compute the correlation matrix</span></span>
<span id="cb239-5"><a href="exercise-answers.html#cb239-5" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_outreach)</span>
<span id="cb239-6"><a href="exercise-answers.html#cb239-6" tabindex="-1"></a></span>
<span id="cb239-7"><a href="exercise-answers.html#cb239-7" tabindex="-1"></a><span class="co"># Visualize the correlation matrix</span></span>
<span id="cb239-8"><a href="exercise-answers.html#cb239-8" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, <span class="at">method =</span> <span class="st">&quot;circle&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-146-1.png" width="672" /></p>
<blockquote>
<p>There is a strong positive correlation between the number of crimes and the number of community outreach programmes.</p>
</blockquote>
</div>
</div>
<div id="chapter-8" class="section level2 unnumbered hasAnchor">
<h2>Chapter 8<a href="exercise-answers.html#chapter-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="exercise-8.1" class="section level3 unnumbered hasAnchor">
<h3>Exercise 8.1<a href="exercise-answers.html#exercise-8.1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Residential burglaries are on the up and you want to assess which factors are contributing to the increase. Using the following dataset data_burglaries perform a multiple linear regression</p>
<blockquote>
<p>The code has been produced here but the interpretation and summary are left to the reader. The code displayed below performs a stepwise linear regression, going outside the bounds of the original treaching. The assumptions are then tested and a box-cox transformation applied before recompleting the regression modelling.</p>
</blockquote>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="exercise-answers.html#cb240-1" tabindex="-1"></a><span class="co">#Load dplyr</span></span>
<span id="cb240-2"><a href="exercise-answers.html#cb240-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb240-3"><a href="exercise-answers.html#cb240-3" tabindex="-1"></a></span>
<span id="cb240-4"><a href="exercise-answers.html#cb240-4" tabindex="-1"></a><span class="co"># Load the dataset from csv file</span></span>
<span id="cb240-5"><a href="exercise-answers.html#cb240-5" tabindex="-1"></a>data_burglaries <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;data/data_burglaries.csv&#39;</span>)</span>
<span id="cb240-6"><a href="exercise-answers.html#cb240-6" tabindex="-1"></a></span>
<span id="cb240-7"><a href="exercise-answers.html#cb240-7" tabindex="-1"></a><span class="co"># Data Overview - Check variable type</span></span>
<span id="cb240-8"><a href="exercise-answers.html#cb240-8" tabindex="-1"></a><span class="fu">head</span>(data_burglaries)</span></code></pre></div>
<pre><code>##   burglaries police_patrols avg_income neighbourhood_watch vacancy_rate full_time_employment avg_household_size crime_rate
## 1        124              8   48645.21                   0   0.04594669            0.5158787           3.440589   2.315514
## 2        197              9   53218.08                   1   0.05548609            0.5732118           2.028175   5.005712
## 3         45             14   38922.08                   0   0.01165823            0.8515365           3.699788   4.557348
## 4         58             10   41384.17                   0   0.10697253            0.5327804           2.971972   4.977908
## 5         18             10   30244.76                   0   0.08263841            0.8109035           3.262457   3.849165
## 6        106             15   47256.12                   1   0.02037981            0.9686637           3.311017   3.626369</code></pre>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="exercise-answers.html#cb242-1" tabindex="-1"></a><span class="co"># Check for Missing Values</span></span>
<span id="cb242-2"><a href="exercise-answers.html#cb242-2" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">is.na</span>(data_burglaries))</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="exercise-answers.html#cb244-1" tabindex="-1"></a><span class="co"># Convert Neighbourhood Watch to factor</span></span>
<span id="cb244-2"><a href="exercise-answers.html#cb244-2" tabindex="-1"></a>data_burglaries<span class="sc">$</span>neighbourhood_watch <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_burglaries<span class="sc">$</span>neighbourhood_watch)</span>
<span id="cb244-3"><a href="exercise-answers.html#cb244-3" tabindex="-1"></a></span>
<span id="cb244-4"><a href="exercise-answers.html#cb244-4" tabindex="-1"></a><span class="do">## Perform a Stepwise Linear Regression</span></span>
<span id="cb244-5"><a href="exercise-answers.html#cb244-5" tabindex="-1"></a><span class="co">#  A stepwise linear regression uses a full model and a null model and</span></span>
<span id="cb244-6"><a href="exercise-answers.html#cb244-6" tabindex="-1"></a><span class="co">#  adds or remove variables until it has found the best model.</span></span>
<span id="cb244-7"><a href="exercise-answers.html#cb244-7" tabindex="-1"></a></span>
<span id="cb244-8"><a href="exercise-answers.html#cb244-8" tabindex="-1"></a><span class="co"># Fit a full model</span></span>
<span id="cb244-9"><a href="exercise-answers.html#cb244-9" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(burglaries <span class="sc">~</span> ., <span class="at">data =</span> data_burglaries)</span>
<span id="cb244-10"><a href="exercise-answers.html#cb244-10" tabindex="-1"></a></span>
<span id="cb244-11"><a href="exercise-answers.html#cb244-11" tabindex="-1"></a><span class="co"># Fit a null model</span></span>
<span id="cb244-12"><a href="exercise-answers.html#cb244-12" tabindex="-1"></a>null_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(burglaries <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> data_burglaries)</span>
<span id="cb244-13"><a href="exercise-answers.html#cb244-13" tabindex="-1"></a></span>
<span id="cb244-14"><a href="exercise-answers.html#cb244-14" tabindex="-1"></a><span class="co"># Perform stepwise regression using both forward and backward selection</span></span>
<span id="cb244-15"><a href="exercise-answers.html#cb244-15" tabindex="-1"></a>stepwise_model <span class="ot">&lt;-</span> <span class="fu">step</span>(null_model, </span>
<span id="cb244-16"><a href="exercise-answers.html#cb244-16" tabindex="-1"></a>                       <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> null_model, <span class="at">upper =</span> full_model),</span>
<span id="cb244-17"><a href="exercise-answers.html#cb244-17" tabindex="-1"></a>                       <span class="at">direction =</span> <span class="st">&quot;both&quot;</span>)</span></code></pre></div>
<pre><code>## Start:  AIC=2708.56
## burglaries ~ 1
## 
##                        Df Sum of Sq       RSS    AIC
## + avg_income            1  72190727  78558628 2580.2
## &lt;none&gt;                              150749355 2708.6
## + crime_rate            1    706661 150042694 2709.6
## + police_patrols        1    649189 150100166 2709.7
## + avg_household_size    1    469544 150279811 2709.9
## + full_time_employment  1     97074 150652281 2710.4
## + vacancy_rate          1     75824 150673531 2710.5
## + neighbourhood_watch   1     36248 150713107 2710.5
## 
## Step:  AIC=2580.21
## burglaries ~ avg_income
## 
##                        Df Sum of Sq       RSS    AIC
## &lt;none&gt;                               78558628 2580.2
## + full_time_employment  1    282352  78276276 2581.5
## + avg_household_size    1    127046  78431582 2581.9
## + neighbourhood_watch   1     70409  78488220 2582.0
## + vacancy_rate          1     18141  78540487 2582.2
## + police_patrols        1      9281  78549347 2582.2
## + crime_rate            1       279  78558349 2582.2
## - avg_income            1  72190727 150749355 2708.6</code></pre>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="exercise-answers.html#cb246-1" tabindex="-1"></a><span class="co"># View the results</span></span>
<span id="cb246-2"><a href="exercise-answers.html#cb246-2" tabindex="-1"></a><span class="fu">summary</span>(stepwise_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = burglaries ~ avg_income, data = data_burglaries)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -437.7 -354.9 -199.1   99.7 4640.3 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.593e+03  1.567e+02  -10.17   &lt;2e-16 ***
## avg_income   4.020e-02  2.980e-03   13.49   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 629.9 on 198 degrees of freedom
## Multiple R-squared:  0.4789, Adjusted R-squared:  0.4762 
## F-statistic:   182 on 1 and 198 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="exercise-answers.html#cb248-1" tabindex="-1"></a><span class="do">### Check Assumptions</span></span>
<span id="cb248-2"><a href="exercise-answers.html#cb248-2" tabindex="-1"></a></span>
<span id="cb248-3"><a href="exercise-answers.html#cb248-3" tabindex="-1"></a><span class="do">## Linearity</span></span>
<span id="cb248-4"><a href="exercise-answers.html#cb248-4" tabindex="-1"></a><span class="co">#Plot residuals vs fitted values</span></span>
<span id="cb248-5"><a href="exercise-answers.html#cb248-5" tabindex="-1"></a><span class="fu">plot</span>(stepwise_model<span class="sc">$</span>fitted.values, <span class="fu">resid</span>(stepwise_model))</span>
<span id="cb248-6"><a href="exercise-answers.html#cb248-6" tabindex="-1"></a><span class="co">#Add horizontal line at y = 0</span></span>
<span id="cb248-7"><a href="exercise-answers.html#cb248-7" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-147-1.png" width="672" /></p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="exercise-answers.html#cb249-1" tabindex="-1"></a><span class="do">## Normality of Residuals</span></span>
<span id="cb249-2"><a href="exercise-answers.html#cb249-2" tabindex="-1"></a><span class="co">#Create a Q-Q plot</span></span>
<span id="cb249-3"><a href="exercise-answers.html#cb249-3" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(stepwise_model))</span>
<span id="cb249-4"><a href="exercise-answers.html#cb249-4" tabindex="-1"></a><span class="co">#Add Q-Q line</span></span>
<span id="cb249-5"><a href="exercise-answers.html#cb249-5" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">resid</span>(stepwise_model), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-147-2.png" width="672" /></p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="exercise-answers.html#cb250-1" tabindex="-1"></a><span class="do">## Heteroscedasticity</span></span>
<span id="cb250-2"><a href="exercise-answers.html#cb250-2" tabindex="-1"></a><span class="co">#Plot Scale-Location plot</span></span>
<span id="cb250-3"><a href="exercise-answers.html#cb250-3" tabindex="-1"></a><span class="fu">plot</span>(stepwise_model, <span class="at">which =</span> <span class="dv">3</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-147-3.png" width="672" /></p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="exercise-answers.html#cb251-1" tabindex="-1"></a><span class="do">## Independence of Errors</span></span>
<span id="cb251-2"><a href="exercise-answers.html#cb251-2" tabindex="-1"></a><span class="co">#Load the car library</span></span>
<span id="cb251-3"><a href="exercise-answers.html#cb251-3" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb251-4"><a href="exercise-answers.html#cb251-4" tabindex="-1"></a><span class="co">#Run the DurbinWatson test</span></span>
<span id="cb251-5"><a href="exercise-answers.html#cb251-5" tabindex="-1"></a><span class="fu">durbinWatsonTest</span>(stepwise_model)</span></code></pre></div>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1      0.03975713      1.919275   0.512
##  Alternative hypothesis: rho != 0</code></pre>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="exercise-answers.html#cb253-1" tabindex="-1"></a><span class="do">## Variance Inflation Factors</span></span>
<span id="cb253-2"><a href="exercise-answers.html#cb253-2" tabindex="-1"></a><span class="co">#Calculate the Variance Inflation Factors</span></span>
<span id="cb253-3"><a href="exercise-answers.html#cb253-3" tabindex="-1"></a><span class="co">#vif(stepwise_model)</span></span>
<span id="cb253-4"><a href="exercise-answers.html#cb253-4" tabindex="-1"></a></span>
<span id="cb253-5"><a href="exercise-answers.html#cb253-5" tabindex="-1"></a><span class="do">## Box-Cox Transformation</span></span>
<span id="cb253-6"><a href="exercise-answers.html#cb253-6" tabindex="-1"></a><span class="co">#Load MASS Library</span></span>
<span id="cb253-7"><a href="exercise-answers.html#cb253-7" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="exercise-answers.html#cb256-1" tabindex="-1"></a><span class="co">#Perform the Box-Cox transformation</span></span>
<span id="cb256-2"><a href="exercise-answers.html#cb256-2" tabindex="-1"></a>bc <span class="ot">&lt;-</span> <span class="fu">boxcox</span>(stepwise_model, <span class="at">lambda =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-147-4.png" width="672" /></p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="exercise-answers.html#cb257-1" tabindex="-1"></a><span class="co">#Find the optimal lambda</span></span>
<span id="cb257-2"><a href="exercise-answers.html#cb257-2" tabindex="-1"></a>optimal_lambda <span class="ot">&lt;-</span> bc<span class="sc">$</span>x[<span class="fu">which.max</span>(bc<span class="sc">$</span>y)]</span>
<span id="cb257-3"><a href="exercise-answers.html#cb257-3" tabindex="-1"></a></span>
<span id="cb257-4"><a href="exercise-answers.html#cb257-4" tabindex="-1"></a><span class="co">#Print optimal lambda</span></span>
<span id="cb257-5"><a href="exercise-answers.html#cb257-5" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Optimal lambda:&quot;</span>, optimal_lambda))</span></code></pre></div>
<pre><code>## [1] &quot;Optimal lambda: 0.0202020202020203&quot;</code></pre>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="exercise-answers.html#cb259-1" tabindex="-1"></a><span class="co">#Apply the Box-Cox transformation</span></span>
<span id="cb259-2"><a href="exercise-answers.html#cb259-2" tabindex="-1"></a>data_burglaries<span class="sc">$</span>burglaries_transformed <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(optimal_lambda <span class="sc">==</span> <span class="dv">0</span>,</span>
<span id="cb259-3"><a href="exercise-answers.html#cb259-3" tabindex="-1"></a>                                                 <span class="fu">log</span>(data_burglaries<span class="sc">$</span>burglaries),</span>
<span id="cb259-4"><a href="exercise-answers.html#cb259-4" tabindex="-1"></a>                                                 (data_burglaries<span class="sc">$</span>burglaries<span class="sc">^</span>optimal_lambda <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> optimal_lambda)</span>
<span id="cb259-5"><a href="exercise-answers.html#cb259-5" tabindex="-1"></a></span>
<span id="cb259-6"><a href="exercise-answers.html#cb259-6" tabindex="-1"></a><span class="co"># Fit a full model</span></span>
<span id="cb259-7"><a href="exercise-answers.html#cb259-7" tabindex="-1"></a>full_model_trans <span class="ot">&lt;-</span> <span class="fu">lm</span>(burglaries_transformed <span class="sc">~</span> ., <span class="at">data =</span> data_burglaries)</span>
<span id="cb259-8"><a href="exercise-answers.html#cb259-8" tabindex="-1"></a></span>
<span id="cb259-9"><a href="exercise-answers.html#cb259-9" tabindex="-1"></a><span class="co"># Fit a null model</span></span>
<span id="cb259-10"><a href="exercise-answers.html#cb259-10" tabindex="-1"></a>null_model_trans <span class="ot">&lt;-</span> <span class="fu">lm</span>(burglaries_transformed <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> data_burglaries)</span>
<span id="cb259-11"><a href="exercise-answers.html#cb259-11" tabindex="-1"></a></span>
<span id="cb259-12"><a href="exercise-answers.html#cb259-12" tabindex="-1"></a><span class="co"># Perform stepwise regression using both forward and backward selection</span></span>
<span id="cb259-13"><a href="exercise-answers.html#cb259-13" tabindex="-1"></a>transformed_model <span class="ot">&lt;-</span> <span class="fu">step</span>(null_model_trans,</span>
<span id="cb259-14"><a href="exercise-answers.html#cb259-14" tabindex="-1"></a>                          <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> null_model_trans, <span class="at">upper =</span> full_model_trans),</span>
<span id="cb259-15"><a href="exercise-answers.html#cb259-15" tabindex="-1"></a>                          <span class="at">direction =</span> <span class="st">&quot;both&quot;</span>)</span></code></pre></div>
<pre><code>## Start:  AIC=-13861.95
## burglaries_transformed ~ 1</code></pre>
<pre><code>## Warning: attempting model selection on an essentially perfect fit is nonsense</code></pre>
<pre><code>##                        Df  Sum of Sq        RSS    AIC
## + full_time_employment  1 2.1627e-30 1.5482e-28 -13863
## &lt;none&gt;                               1.5698e-28 -13862
## + crime_rate            1 1.3196e-30 1.5566e-28 -13862
## + neighbourhood_watch   1 8.3766e-31 1.5615e-28 -13861
## + avg_household_size    1 3.8680e-31 1.5660e-28 -13860
## + vacancy_rate          1 2.9754e-31 1.5669e-28 -13860
## + police_patrols        1 2.7859e-31 1.5670e-28 -13860
## + burglaries            1 1.0033e-31 1.5688e-28 -13860
## + avg_income            1 1.1260e-32 1.5697e-28 -13860
## 
## Step:  AIC=-13862.72
## burglaries_transformed ~ full_time_employment</code></pre>
<pre><code>## Warning: attempting model selection on an essentially perfect fit is nonsense
## Warning: attempting model selection on an essentially perfect fit is nonsense</code></pre>
<pre><code>##                        Df  Sum of Sq        RSS    AIC
## + crime_rate            1 1.6739e-30 1.5315e-28 -13863
## &lt;none&gt;                               1.5482e-28 -13863
## + neighbourhood_watch   1 1.3027e-30 1.5352e-28 -13862
## - full_time_employment  1 2.1627e-30 1.5698e-28 -13862
## + vacancy_rate          1 3.6578e-31 1.5445e-28 -13861
## + avg_household_size    1 3.5445e-31 1.5447e-28 -13861
## + police_patrols        1 3.5320e-31 1.5447e-28 -13861
## + burglaries            1 7.8130e-32 1.5474e-28 -13861
## + avg_income            1 2.0780e-32 1.5480e-28 -13861
## 
## Step:  AIC=-13862.89
## burglaries_transformed ~ full_time_employment + crime_rate</code></pre>
<pre><code>## Warning: attempting model selection on an essentially perfect fit is nonsense
## Warning: attempting model selection on an essentially perfect fit is nonsense</code></pre>
<pre><code>##                        Df  Sum of Sq        RSS    AIC
## &lt;none&gt;                               1.5315e-28 -13863
## - crime_rate            1 1.6739e-30 1.5482e-28 -13863
## + neighbourhood_watch   1 1.2242e-30 1.5192e-28 -13862
## - full_time_employment  1 2.5170e-30 1.5566e-28 -13862
## + vacancy_rate          1 3.9426e-31 1.5275e-28 -13861
## + police_patrols        1 2.8213e-31 1.5286e-28 -13861
## + avg_household_size    1 2.5114e-31 1.5290e-28 -13861
## + burglaries            1 3.5290e-32 1.5311e-28 -13861
## + avg_income            1 2.6000e-34 1.5315e-28 -13861</code></pre>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="exercise-answers.html#cb267-1" tabindex="-1"></a><span class="co"># View the summary of the transformed model</span></span>
<span id="cb267-2"><a href="exercise-answers.html#cb267-2" tabindex="-1"></a><span class="fu">summary</span>(transformed_model)</span></code></pre></div>
<pre><code>## Warning in summary.lm(transformed_model): essentially perfect fit: summary may be unreliable</code></pre>
<pre><code>## 
## Call:
## lm(formula = burglaries_transformed ~ full_time_employment + 
##     crime_rate, data = data_burglaries)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -1.219e-14 -2.920e-17  6.130e-17  1.650e-16  4.187e-16 
## 
## Coefficients:
##                       Estimate Std. Error   t value Pr(&gt;|t|)    
## (Intercept)          5.063e+00  3.859e-16 1.312e+16   &lt;2e-16 ***
## full_time_employment 8.097e-16  4.500e-16 1.799e+00   0.0735 .  
## crime_rate           4.414e-17  3.008e-17 1.467e+00   0.1439    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.817e-16 on 197 degrees of freedom
## Multiple R-squared:  0.5024, Adjusted R-squared:  0.4973 
## F-statistic: 99.45 on 2 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="exercise-8.2" class="section level3 unnumbered hasAnchor">
<h3>Exercise 8.2<a href="exercise-answers.html#exercise-8.2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The Police Dispatch Team prioritise some calls as “high-priority” to ensure a faster response and better allocation of resources. You have been tasked with determining what factors lead to a crime being categorised as “high-priority” or not. Using the following dataset data_response perform a logistic regression to identify which factors affect the high-priority crime decision.</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="exercise-answers.html#cb270-1" tabindex="-1"></a><span class="co"># Load the dataset from csv file</span></span>
<span id="cb270-2"><a href="exercise-answers.html#cb270-2" tabindex="-1"></a>data_response <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;data/data_response.csv&#39;</span>)</span>
<span id="cb270-3"><a href="exercise-answers.html#cb270-3" tabindex="-1"></a></span>
<span id="cb270-4"><a href="exercise-answers.html#cb270-4" tabindex="-1"></a><span class="co"># Data Overview - Check variable type</span></span>
<span id="cb270-5"><a href="exercise-answers.html#cb270-5" tabindex="-1"></a><span class="fu">head</span>(data_response)</span></code></pre></div>
<pre><code>##   High_Priority Crime_Severity Weapon_Involved Time_of_Day High_Crime_Area
## 1             1              2               1         Day               1
## 2             0              3               0         Day               1
## 3             1              8               1       Night               1
## 4             1              9               0       Night               0
## 5             1              8               1       Night               0
## 6             1              4               0         Day               1</code></pre>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="exercise-answers.html#cb272-1" tabindex="-1"></a><span class="co">#Convert factor variables</span></span>
<span id="cb272-2"><a href="exercise-answers.html#cb272-2" tabindex="-1"></a>data_response<span class="sc">$</span>Weapon_Involved <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_response<span class="sc">$</span>Weapon_Involved)</span>
<span id="cb272-3"><a href="exercise-answers.html#cb272-3" tabindex="-1"></a>data_response<span class="sc">$</span>Time_of_Day <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_response<span class="sc">$</span>Time_of_Day)</span>
<span id="cb272-4"><a href="exercise-answers.html#cb272-4" tabindex="-1"></a>data_response<span class="sc">$</span>High_Crime_Area <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_response<span class="sc">$</span>High_Crime_Area)</span>
<span id="cb272-5"><a href="exercise-answers.html#cb272-5" tabindex="-1"></a></span>
<span id="cb272-6"><a href="exercise-answers.html#cb272-6" tabindex="-1"></a><span class="co">#Create a logistic regression model</span></span>
<span id="cb272-7"><a href="exercise-answers.html#cb272-7" tabindex="-1"></a>model_logistic <span class="ot">&lt;-</span> <span class="fu">glm</span>(High_Priority <span class="sc">~</span> ., <span class="at">data =</span> data_response, <span class="at">family =</span> binomial)</span>
<span id="cb272-8"><a href="exercise-answers.html#cb272-8" tabindex="-1"></a></span>
<span id="cb272-9"><a href="exercise-answers.html#cb272-9" tabindex="-1"></a><span class="co">#Produce model summary</span></span>
<span id="cb272-10"><a href="exercise-answers.html#cb272-10" tabindex="-1"></a><span class="fu">summary</span>(model_logistic)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = High_Priority ~ ., family = binomial, data = data_response)
## 
## Coefficients:
##                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)      -0.83922    0.59431  -1.412 0.157921    
## Crime_Severity    0.22292    0.08811   2.530 0.011407 *  
## Weapon_Involved1  1.87159    0.53179   3.519 0.000433 ***
## Time_of_DayNight  1.03824    0.46179   2.248 0.024556 *  
## High_Crime_Area1  0.69768    0.44035   1.584 0.113107    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 169.08  on 199  degrees of freedom
## Residual deviance: 138.41  on 195  degrees of freedom
## AIC: 148.41
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="exercise-answers.html#cb274-1" tabindex="-1"></a><span class="co"># Convert coefficients to odds ratios</span></span>
<span id="cb274-2"><a href="exercise-answers.html#cb274-2" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model_logistic))</span></code></pre></div>
<pre><code>##      (Intercept)   Crime_Severity Weapon_Involved1 Time_of_DayNight High_Crime_Area1 
##        0.4320481        1.2497259        6.4986325        2.8242367        2.0090799</code></pre>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="exercise-answers.html#cb276-1" tabindex="-1"></a><span class="do">## Check Model Assumptions</span></span>
<span id="cb276-2"><a href="exercise-answers.html#cb276-2" tabindex="-1"></a><span class="co"># Linearity of Logit</span></span>
<span id="cb276-3"><a href="exercise-answers.html#cb276-3" tabindex="-1"></a><span class="co"># Predicted probabilities</span></span>
<span id="cb276-4"><a href="exercise-answers.html#cb276-4" tabindex="-1"></a>preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_logistic, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb276-5"><a href="exercise-answers.html#cb276-5" tabindex="-1"></a></span>
<span id="cb276-6"><a href="exercise-answers.html#cb276-6" tabindex="-1"></a><span class="co"># Logit transformation</span></span>
<span id="cb276-7"><a href="exercise-answers.html#cb276-7" tabindex="-1"></a>logit <span class="ot">&lt;-</span> <span class="fu">log</span>(preds <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> preds))</span>
<span id="cb276-8"><a href="exercise-answers.html#cb276-8" tabindex="-1"></a></span>
<span id="cb276-9"><a href="exercise-answers.html#cb276-9" tabindex="-1"></a><span class="co"># Plot logit vs predictor</span></span>
<span id="cb276-10"><a href="exercise-answers.html#cb276-10" tabindex="-1"></a><span class="fu">plot</span>(data_arrests<span class="sc">$</span>Police_On_Duty, logit,</span>
<span id="cb276-11"><a href="exercise-answers.html#cb276-11" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Police on Duty&quot;</span>,</span>
<span id="cb276-12"><a href="exercise-answers.html#cb276-12" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Logit of Predicted Probability&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-148-1.png" width="672" /></p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="exercise-answers.html#cb277-1" tabindex="-1"></a><span class="co"># Multicolinearity</span></span>
<span id="cb277-2"><a href="exercise-answers.html#cb277-2" tabindex="-1"></a><span class="co">#Calculate Variance Inflation Factors</span></span>
<span id="cb277-3"><a href="exercise-answers.html#cb277-3" tabindex="-1"></a><span class="fu">vif</span>(model_logistic)</span></code></pre></div>
<pre><code>##  Crime_Severity Weapon_Involved     Time_of_Day High_Crime_Area 
##        1.014402        1.017584        1.026008        1.016278</code></pre>
<blockquote>
<p>The model shows that incidents where a weapon is involved, the potential crime severity, and it being night time lead to an increased chance of a call being classed as high priority. The model assumptions have been displayed using code and it is left as a task of the reader to assess them.</p>
</blockquote>
</div>
</div>
<div id="chapter-9" class="section level2 unnumbered hasAnchor">
<h2>Chapter 9<a href="exercise-answers.html#chapter-9" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="exercise-9.1" class="section level3 unnumbered hasAnchor">
<h3>Exercise 9.1<a href="exercise-answers.html#exercise-9.1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recreate these steps using the 2018 London Wards Shapefiles available at Statistical GIS Boundary Files for London. You should get the output shown below.</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="exercise-answers.html#cb279-1" tabindex="-1"></a><span class="co">#Load the sf package</span></span>
<span id="cb279-2"><a href="exercise-answers.html#cb279-2" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb279-3"><a href="exercise-answers.html#cb279-3" tabindex="-1"></a></span>
<span id="cb279-4"><a href="exercise-answers.html#cb279-4" tabindex="-1"></a><span class="co"># Import a shapefile</span></span>
<span id="cb279-5"><a href="exercise-answers.html#cb279-5" tabindex="-1"></a>spatial_data <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">&quot;data/london-wards-2018/London_Ward.shp&quot;</span>)</span></code></pre></div>
<pre><code>## Reading layer `London_Ward&#39; from data source `D:\Daniel\My Documents\MOPAC\Introduction to R\data\london-wards-2018\London_Ward.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 657 features and 6 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 503568.2 ymin: 155850.8 xmax: 561957.5 ymax: 200933.9
## Projected CRS: OSGB36 / British National Grid</code></pre>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="exercise-answers.html#cb281-1" tabindex="-1"></a><span class="co"># View the structure of the spatial data</span></span>
<span id="cb281-2"><a href="exercise-answers.html#cb281-2" tabindex="-1"></a><span class="fu">head</span>(spatial_data)</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 6 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 516362.6 ymin: 159907.4 xmax: 522194.7 ymax: 172367
## Projected CRS: OSGB36 / British National Grid
##                     NAME  GSS_CODE             DISTRICT LAGSSCODE HECTARES NONLD_AREA                       geometry
## 1      Chessington South E05000405 Kingston upon Thames E09000021  755.173          0 POLYGON ((516401.6 160201.8...
## 2 Tolworth and Hook Rise E05000414 Kingston upon Thames E09000021  259.464          0 POLYGON ((519553 164295.6, ...
## 3             Berrylands E05000401 Kingston upon Thames E09000021  145.390          0 POLYGON ((518107.5 167303.4...
## 4              Alexandra E05000400 Kingston upon Thames E09000021  268.506          0 POLYGON ((520336.7 165105.5...
## 5               Beverley E05000402 Kingston upon Thames E09000021  187.821          0 POLYGON ((521201.2 169275.5...
## 6            Coombe Hill E05000406 Kingston upon Thames E09000021  442.170          0 POLYGON ((521296.5 172258.3...</code></pre>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="exercise-answers.html#cb283-1" tabindex="-1"></a><span class="co"># Plot the spatial data</span></span>
<span id="cb283-2"><a href="exercise-answers.html#cb283-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(spatial_data))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-149-1.png" width="672" /></p>
</div>
<div id="exercise-9.2" class="section level3 unnumbered hasAnchor">
<h3>Exercise 9.2<a href="exercise-answers.html#exercise-9.2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Go to the EPSG website and explore the different coordinate options available for the United Kingdom. What is the EPSG code of the British National Grid projection?</p>
<blockquote>
<p><a href="https://epsg.io/27700">EPSG:27700</a> - OSGB36 / British National Grid – United Kingdom Ordnance Survey</p>
</blockquote>
</div>
<div id="exercise-9.3" class="section level3 unnumbered hasAnchor">
<h3>Exercise 9.3<a href="exercise-answers.html#exercise-9.3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Use the London 2018 Ward Shapefile to create a map of London using ggplot2. Add a light blue point at (51.503618787766060, -0.09860017990274424) to represent the MOPAC offices. These coordinates were taken from Google Maps which uses a WGS84 projection which may differ from the projection used by the London Shapefile.</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="exercise-answers.html#cb284-1" tabindex="-1"></a>data_points <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">longitude =</span> <span class="sc">-</span><span class="fl">0.09860017990274424</span>, <span class="at">latitude =</span> <span class="fl">51.503618787766060</span>)</span>
<span id="cb284-2"><a href="exercise-answers.html#cb284-2" tabindex="-1"></a></span>
<span id="cb284-3"><a href="exercise-answers.html#cb284-3" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb284-4"><a href="exercise-answers.html#cb284-4" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> spatial_data) <span class="sc">+</span></span>
<span id="cb284-5"><a href="exercise-answers.html#cb284-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> data_points, <span class="fu">aes</span>(<span class="at">x =</span> longitude, <span class="at">y =</span> latitude), <span class="at">color =</span> <span class="st">&quot;lightblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb284-6"><a href="exercise-answers.html#cb284-6" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">crs =</span> <span class="fu">st_crs</span>(<span class="dv">4326</span>)) <span class="sc">+</span></span>
<span id="cb284-7"><a href="exercise-answers.html#cb284-7" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Geographic Ward Level Plot of London&quot;</span>, <span class="at">subtitle =</span> <span class="st">&quot;With a Light Blue Marker Indicating MOPAC HQ&quot;</span>) <span class="sc">+</span></span>
<span id="cb284-8"><a href="exercise-answers.html#cb284-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-150-1.png" width="672" /></p>
</div>
<div id="exercise-9.4" class="section level3 unnumbered hasAnchor">
<h3>Exercise 9.4<a href="exercise-answers.html#exercise-9.4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The British Transport Police have provided you with a number of crimes reported at varying locations across London. You need to identify which Borough they have occurred in.</p>
<p>Longitude Latitude Borough
-0.19611111405556494 51.375258353438184 ?
-0.30174186589110447 51.46320906930937 ?
-0.19565513135661436 51.487172486590836 ?
-0.13840606266909572 51.46153797665847 ?
-0.09291579752832058 51.37534709116438 ?
-0.13321537011710344 51.528459469086386 ?</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="exercise-answers.html#cb285-1" tabindex="-1"></a>btp_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">longitude =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.19611111405556494</span>,</span>
<span id="cb285-2"><a href="exercise-answers.html#cb285-2" tabindex="-1"></a>                                     <span class="sc">-</span><span class="fl">0.30174186589110447</span>,</span>
<span id="cb285-3"><a href="exercise-answers.html#cb285-3" tabindex="-1"></a>                                     <span class="sc">-</span><span class="fl">0.19565513135661436</span>,</span>
<span id="cb285-4"><a href="exercise-answers.html#cb285-4" tabindex="-1"></a>                                     <span class="sc">-</span><span class="fl">0.13840606266909572</span>,</span>
<span id="cb285-5"><a href="exercise-answers.html#cb285-5" tabindex="-1"></a>                                     <span class="sc">-</span><span class="fl">0.09291579752832058</span>,</span>
<span id="cb285-6"><a href="exercise-answers.html#cb285-6" tabindex="-1"></a>                                     <span class="sc">-</span><span class="fl">0.13321537011710344</span>),</span>
<span id="cb285-7"><a href="exercise-answers.html#cb285-7" tabindex="-1"></a>                        <span class="at">latitude  =</span> <span class="fu">c</span>(<span class="fl">51.375258353438184</span>,</span>
<span id="cb285-8"><a href="exercise-answers.html#cb285-8" tabindex="-1"></a>                                      <span class="fl">51.46320906930937</span>,</span>
<span id="cb285-9"><a href="exercise-answers.html#cb285-9" tabindex="-1"></a>                                      <span class="fl">51.487172486590836</span>,</span>
<span id="cb285-10"><a href="exercise-answers.html#cb285-10" tabindex="-1"></a>                                      <span class="fl">51.46153797665847</span>,</span>
<span id="cb285-11"><a href="exercise-answers.html#cb285-11" tabindex="-1"></a>                                      <span class="fl">51.37534709116438</span>,</span>
<span id="cb285-12"><a href="exercise-answers.html#cb285-12" tabindex="-1"></a>                                      <span class="fl">51.528459469086386</span>)</span>
<span id="cb285-13"><a href="exercise-answers.html#cb285-13" tabindex="-1"></a>                          )</span>
<span id="cb285-14"><a href="exercise-answers.html#cb285-14" tabindex="-1"></a></span>
<span id="cb285-15"><a href="exercise-answers.html#cb285-15" tabindex="-1"></a><span class="co"># Convert the dataframe to a spatial sf object</span></span>
<span id="cb285-16"><a href="exercise-answers.html#cb285-16" tabindex="-1"></a>london_coords_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(btp_data, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">&quot;longitude&quot;</span>, <span class="st">&quot;latitude&quot;</span>), <span class="at">crs =</span> <span class="dv">4326</span>)</span>
<span id="cb285-17"><a href="exercise-answers.html#cb285-17" tabindex="-1"></a></span>
<span id="cb285-18"><a href="exercise-answers.html#cb285-18" tabindex="-1"></a><span class="co">#Before we can do this both spatial objects need to be in the same CRS</span></span>
<span id="cb285-19"><a href="exercise-answers.html#cb285-19" tabindex="-1"></a>spatial_data_wsg <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(spatial_data, <span class="dv">4326</span>)</span>
<span id="cb285-20"><a href="exercise-answers.html#cb285-20" tabindex="-1"></a></span>
<span id="cb285-21"><a href="exercise-answers.html#cb285-21" tabindex="-1"></a><span class="co">#Check if points fall in polygon</span></span>
<span id="cb285-22"><a href="exercise-answers.html#cb285-22" tabindex="-1"></a>points_in_polygons <span class="ot">&lt;-</span> <span class="fu">st_within</span>(london_coords_sf, spatial_data_wsg)</span>
<span id="cb285-23"><a href="exercise-answers.html#cb285-23" tabindex="-1"></a></span>
<span id="cb285-24"><a href="exercise-answers.html#cb285-24" tabindex="-1"></a><span class="co"># Extract the names of the areas where each point is located</span></span>
<span id="cb285-25"><a href="exercise-answers.html#cb285-25" tabindex="-1"></a>area_names <span class="ot">&lt;-</span> <span class="fu">sapply</span>(points_in_polygons, <span class="cf">function</span>(x) <span class="cf">if</span>(<span class="fu">length</span>(x) <span class="sc">&gt;</span> <span class="dv">0</span>) spatial_data_wsg<span class="sc">$</span>NAME[x] <span class="cf">else</span> <span class="cn">NA</span>)</span>
<span id="cb285-26"><a href="exercise-answers.html#cb285-26" tabindex="-1"></a></span>
<span id="cb285-27"><a href="exercise-answers.html#cb285-27" tabindex="-1"></a><span class="co"># Add the area names to the original points dataframe</span></span>
<span id="cb285-28"><a href="exercise-answers.html#cb285-28" tabindex="-1"></a>london_coords_sf<span class="sc">$</span>NAME <span class="ot">&lt;-</span> area_names</span>
<span id="cb285-29"><a href="exercise-answers.html#cb285-29" tabindex="-1"></a></span>
<span id="cb285-30"><a href="exercise-answers.html#cb285-30" tabindex="-1"></a><span class="co"># View the updated dataframe with area names</span></span>
<span id="cb285-31"><a href="exercise-answers.html#cb285-31" tabindex="-1"></a><span class="fu">head</span>(london_coords_sf)</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 1 field
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -0.3017419 ymin: 51.37526 xmax: -0.0929158 ymax: 51.52846
## Geodetic CRS:  WGS 84
##                      geometry            NAME
## 1 POINT (-0.1961111 51.37526)    Sutton North
## 2 POINT (-0.3017419 51.46321)  South Richmond
## 3 POINT (-0.1956551 51.48717) Fulham Broadway
## 4 POINT (-0.1384061 51.46154)    Clapham Town
## 5 POINT (-0.0929158 51.37535)       Fairfield
## 6 POINT (-0.1332154 51.52846)   Regent&#39;s Park</code></pre>
</div>
<div id="exercise-9.5" class="section level3 unnumbered hasAnchor">
<h3>Exercise 9.5<a href="exercise-answers.html#exercise-9.5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Create a choropleth map of London visualising the Turnout.at.Mayoral.election…2012.</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="exercise-answers.html#cb287-1" tabindex="-1"></a><span class="co">#Load the ward profiles dataset</span></span>
<span id="cb287-2"><a href="exercise-answers.html#cb287-2" tabindex="-1"></a>ward_profiles <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;data/ward_profiles.csv&#39;</span>)</span>
<span id="cb287-3"><a href="exercise-answers.html#cb287-3" tabindex="-1"></a></span>
<span id="cb287-4"><a href="exercise-answers.html#cb287-4" tabindex="-1"></a><span class="co">#Join the demographic data to the Spatial dataset</span></span>
<span id="cb287-5"><a href="exercise-answers.html#cb287-5" tabindex="-1"></a>spatial_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(spatial_data, ward_profiles, <span class="at">by.x =</span> <span class="st">&quot;LAGSSCODE&quot;</span>, <span class="at">by.y =</span> <span class="st">&quot;New.code&quot;</span>)</span>
<span id="cb287-6"><a href="exercise-answers.html#cb287-6" tabindex="-1"></a></span>
<span id="cb287-7"><a href="exercise-answers.html#cb287-7" tabindex="-1"></a><span class="co">#Change variable data type</span></span>
<span id="cb287-8"><a href="exercise-answers.html#cb287-8" tabindex="-1"></a>spatial_data<span class="sc">$</span>voter_turnout <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(spatial_data<span class="sc">$</span>Turnout.at.Mayoral.election...<span class="dv">2012</span>))</span>
<span id="cb287-9"><a href="exercise-answers.html#cb287-9" tabindex="-1"></a></span>
<span id="cb287-10"><a href="exercise-answers.html#cb287-10" tabindex="-1"></a><span class="co">#Create a Choropleth map of Employment Rates</span></span>
<span id="cb287-11"><a href="exercise-answers.html#cb287-11" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> spatial_data) <span class="sc">+</span></span>
<span id="cb287-12"><a href="exercise-answers.html#cb287-12" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> voter_turnout)) <span class="sc">+</span></span>
<span id="cb287-13"><a href="exercise-answers.html#cb287-13" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb287-14"><a href="exercise-answers.html#cb287-14" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Choropleth Map Displaying Voter Turnout at London Mayoral Election&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;Voter Turnout&quot;</span>) <span class="sc">+</span></span>
<span id="cb287-15"><a href="exercise-answers.html#cb287-15" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-152-1.png" width="672" /></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="geographic-mapping-and-spatial-analysis.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/11-answers.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
